    <!-- Default LOGIN and SIGN UP buttons, remove it when user logged in    -->
       <div class="login-panel">
      <ul >
          <li><a class="login-btn" data-toggle="modal" data-target="#loginModal" href="#login">LOGIN</a></li>
          <li><a class="join-now" href="join-page.html">JOIN NOW!</a></li>
      </ul>
      
  </div>
  
  <?php echo $this->partial('/layout/partials/login-modal-box.phtml'); ?>