                     <div class="login-panel loggedin">
                          <ul >
                             <li class="hello-user">Logged in as <?php echo $this->identity()->getUsername(); ?></li>
                              <li><a class="messages" href="#join" >You have 0 unread messages</a></li>
                              <li><a class="help" href="#join" >Help</a></li>
                              <li><a class="logout" href="<?php echo $this->url('logout'); ?>">Logout</a></li>
                          </ul>

                      </div>