     <!--   Login Modal   -->
     <div class="login-box">
         
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModal" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="loginModal">Login</h4>
      </div>
      <div class="modal-body">
        <form id="login-form" action="<?php echo $this->url('login'); ?>" class="login-form" name="login" method="post">
          <div class="form-group">
           
            <input type="text" class="form-control" id="login-name" placeholder="Username">
          </div>
          <div class="form-group">
            
            <input type="password" class="form-control" id="login-password" placeholder="Password">
          </div>
         
        </form>
        
        
        
        <a class="pass-remind" href="#remind">Forgot Password?</a>
      </div>
      
  <!--     Error message     -->  
     
     <p class="login-error">Your username or password were not recognised</p>
     
      
      <div class="modal-footer">
         
        <input id="login-submit" class="login-btn" type="submit" value="LOGIN">
        
      </div>
    </div>
  </div>
</div>
         
         
     </div>
     
     <script>
     $(document).ready(function() {
         $('#login-submit').click(function () {
             $('#login-form').submit();
         });
     });
     </script>