<nav class="navbar navbar-default " role="navigation">
     
     
      <div class="container">
      
<?php if ($this->identity()) : ?>
    <?php echo $this->partial('layout/partials/loggedin.phtml'); ?>
<?php else: ?>
    <?php echo $this->partial('layout/partials/loggedout.phtml'); ?>
<?php endif; ?>
     
     
   <!--  share icons  -->
      
      <div class="share">
          <ul>
              <li><a href="#youtube"><img src="/img/yt.png" alt=""></a></li>
               <li><a href="#twitter"><img src="/img/tw.png" alt=""></a></li>
                <li><a href="#facebook"><img src="/img/fb.png" alt=""></a></li>
              
          </ul>
          
      </div>
      
        <div class="share-mobile">
          <ul>
              <li><a href="#youtube"><img src="/img/yt.png" alt=""></a></li>
               <li><a href="#twitter"><img src="/img/tw.png" alt=""></a></li>
                <li><a href="#facebook"><img src="/img/fb.png" alt=""></a></li>
              
          </ul>
          
      </div>
       
       
         <!--  navbar  -->
         
         
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <a class="navbar-brand" href="index.html"><img src="/img/logo.png" alt=""></a>
        </div>
        
        
        <div id="navbar" class="navbar-collapse collapse">
           
              <!--  navigation list , class "active" is added to the active page  -->
            <ul class="nav navbar-nav">
                <?php echo $this->menuOption('home', 'Home', 'active'); ?>
                <?php echo $this->menuOption('players', 'Players', 'active'); ?>
                <?php echo $this->menuOption('results', 'Results', 'active'); ?>
                <?php echo $this->menuOption('courts', 'Courts', 'active'); ?>
                <?php echo $this->menuOption('competitions', 'Competitions', 'active'); ?>
                <?php echo $this->menuOption('forums', 'Forums', 'active'); ?>
                <?php echo $this->menuOption('myaccount', 'My Account', 'active'); ?>
                <?php echo $this->menuOption('directories', 'Directories', 'active'); ?>
            </ul>
             
        
         

       
        </div><!--/.navbar-collapse -->
        
          
        
      </div>
    </nav>