<!--  
  
  Page jumbotron is used on every single page , consist of news / alerts bar.
  
  Second class for jumbotron give it appropriate image in css ,
  "forum" class for this example should be used only on forum page, so the forum image is displayed.
  
  Full list of classes used :
  
  Page                         Class
  ------                       ------
  Homepage                     .homepage   
  Players                      .players
  Results                      .results
  Courts                       .courts
  Competitions                 .competitions
  Forums                       .forum
  My Account/Join/Help         .account
  Directories                  .directories
  
  
  
  
   
      
   -->
    
      <div class="jumbotron <?php echo $this->jumboClass(); ?>">
     <div class="container">
     
   <!-- news/alert bar   -->
    <div class="information col-sm-12 ">
       <span class="glyphicon glyphicon-info-sign pull-left"></span>
                The Winter 2014/2015 leagues will be published on
            26 January 2015
            
            <a href="#signup">Sign up now !</a>
        
    </div>

      </div>
    </div>