<?php echo $this->doctype(); ?>

<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta name="description" content="">
        <?php echo $this->headTitle('London Tennis'); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/main.css?r=' . rand(1,10000000))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css?r=' . rand(1,10000000))
        ?>
        
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/main.js?r=' . rand(1,10000000))
            ->prependFile($this->basePath() . '/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/vendor/wow.min.js')
            ->prependFile($this->basePath() . '/js/vendor/sc.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

        <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900' rel='stylesheet' type='text/css'>
        
    </head>
    <body>
            <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <?php echo $this->partial('layout/partials/navbar.phtml'); ?>
        
        <?php echo $this->partial(
            $this->routeName() == 'home' ? 
                'layout/partials/home-jumbotron.phtml' :
                'layout/partials/page-jumbotron.phtml'
        ); ?>
        
        <?php echo $this->content; ?>
        
        <?php echo $this->partial('layout/partials/footer.html'); ?>
            
        <?php echo $this->inlineScript() ?>
                 
        <?php echo $this->partial('layout/modal/player-modal.phtml'); ?>
 
    </body>

   
    
</html>
