  <div class="panel-body">
  <ul class="nav-tabs nav">
         <li class="active" >
             <a  href="<?php echo $this->url('myaccount/inbox'); ?>" >Inbox</a>
         </li>
      <li >
          <a href="<?php echo $this->url('myaccount/inbox/sent-messages'); ?>" >Sent Messages</a>
      </li>
   <li>
         <a href="<?php echo $this->url('myaccount/inbox/send-message'); ?>" >Create Message</a>
    </li>
  </ul>
  </div>