<div class="filters">
                               <ul class="nav-tabs nav">
                                      <li   ><a href="<?php echo $this->url('myaccount/dashboard'); ?>">My Dashboard</a></li>
                                      <li   ><a href="<?php echo $this->url('myaccount/inbox'); ?>">My Inbox</a></li>
                                      <li ><a href="<?php echo $this->url('myaccount/settings'); ?>">My Settings</a></li>
                                      <li  ><a href="<?php echo $this->url('myaccount/friends'); ?>">My Friends</a></li>
                                      <li  class="active"  ><a href="<?php echo $this->url('myaccount/dashboard'); ?>">My Block List</a></li>
                                      <li ><a href="<?php echo $this->url('myaccount/calendar'); ?>">My Calendar</a></li>
                                      <li ><a href="<?php echo $this->url('myaccount/entries'); ?>">My Entires</a></li>

                                       </ul>
                                </div>