<div class="container paper">
          
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>MY ACCOUNT</h1>
                      </div>
                      
                      
                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                                <?php echo $this->partial('application/my-account/partials/subnav.phtml');?>
                                
                                <hr>
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-lg-10 col-lg-offset-1">
                               <div class="col-lg-4 col-md-4 col-sm-5">
                                  <div class="panel panel-default avatar-panel ">
  <div class="panel-heading">
    <h3 class="panel-title text-center">Current Avatar</h3>
  </div>
  <div class="panel-body">
    <span class="img-thumb"><img src="img/profile.jpg" alt=""></span>
    <ul class="nav-tabs nav">
        
      <li >
          <a href="" >Change</a>
      </li>
   <li>
         <a href="" >Remove</a>
    </li>
  </ul>
  </div>
</div>
                                 

                                  
                                  <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title text-center">Upcoming Leagues</h3>
  </div>
  <div class="panel-body small-table">
    <table class="table ">
        <tbody>
            <tr>
                <td>Next League :</td>
                <td>Winter 2014/2015</td>
            </tr>
            <tr>
                <td>Starts:</td>
                <td>26 January 2015</td>
            </tr>
            
            <tr>
            
            </tr>
            
        </tbody>
        
    </table>
     <a href="competition-league-sign.html">Click here to sign up !</a>
  </div>
</div>
                                  
                                  <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title text-center">Upcoming Knockouts</h3>
  </div>
  <div class="panel-body small-table">
    <p>The Winter 2015 Knockout Tournament starts on January 11th 2015.
You are not registed for this knockout.</p>
     <a href="competition-league-sign.html">Click here to join!</a>
  </div>
</div>
                                  
                                  <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title text-center">My Results</h3>
  </div>
  <div class="panel-body small-table">
    <p>You have not yet registered any results on the site.</p>
     <a href="competition-league-sign.html">Click here to add result</a>
  </div>
</div>
                                   
                               </div>
                               
                               
                              <!-- Edit Profile text  -->
                               <div class="col-lg-8 col-md-8 col-sm-7">
                                  <div class="panel panel-default edit-profile">
  <div class="panel-heading">
    <h3 class="panel-title text-center">Your profile text</h3>
  </div>
  <div class="panel-body ">
    <textarea class="form-control" name="" id="textarea_profiletext" cols="30" rows="10"></textarea>
     <button type="submit" id="button_profiletext" name="findplayerbutton" class="btn btn-green pull-right">Update profile</button> 
  </div>
</div>
                                 
                                 <div class="panel panel-default edit-profile">
  <div class="panel-heading">
    <h3 class="panel-title text-center">Messages</h3>
  </div>
  
<!--  Message body  -->
  
  <div class="panel-body ">
   <div class="message-panel clearfix">
     <div class="message-profile clearfix">
         <span class="img-thumb small"><img src="img/profile.jpg" alt=""></span>
            <a class="player-name" href="#profilename">Paul Barton</a>
            <p class="pull-left">17 Jan '12</p>
     </div>
        
             <div class="message-content">
                 Welcome to your London Tennis dashboard.
<br><br>
Here you will be updated with site news, messages from other players and match results from members on your friends list.
<br><br>
Why not take a read of the getting started page to get up to speed with the various parts of the London Tennis website.
                 
             </div>
         
          
      
       
       
       
   </div>
     <button type="submit" id="button_profiletext" name="findplayerbutton" class="btn btn-green pull-right"><span class="glyphicon glyphicon-share-alt"></span>Reply</button> 
  </div>
  <hr>
  
 <!--  Message body  -->
  
  <div class="panel-body ">
   <div class="message-panel clearfix">
     <div class="message-profile clearfix">
         <span class="img-thumb small"><img src="img/profile.jpg" alt=""></span>
            <a class="player-name" href="#profilename">Paul Barton</a>
            <p class="pull-left">17 Jan '12</p>
     </div>
        
             <div class="message-content">
               Welcome to your London Tennis dashboard.<br><br>

Here you will be updated with site news, messages from other players and match results from members on your <a href="my-account-friends.html">friends list.</a><br/><br/>

Why not take a read of the <a href="hetting-started.html">getting started</a> page to get up to speed with the various parts of the London Tennis website.
             </div>
         
          
      
       
       
       
   </div>
     <button type="submit" id="button_profiletext" name="findplayerbutton" class="btn btn-green pull-right"><span class="glyphicon glyphicon-share-alt"></span>Reply</button> 
  </div>

  
  
  
  
</div>
                                  
                                   
                               </div>
 
                            </div>
  
                        </div>
                        
                        
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>