<div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>MY ACCOUNT</h1>
                      </div>
                      
                      
                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                                <?php echo $this->partial('application/my-account/partials/subnav.phtml');?>
                                
                                <hr>
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-lg-10 col-lg-offset-1">
                               
                      This page shows the leagues and knockouts you have played in the past and any upcoming competitions for which you have registered.
<br><br>
If you have any questions regarding the leagues or knockouts please let us know or view the about the leagues or about the knockout pages.
                           
                           <hr>
                            </div>
                            
                            <div class="col-lg-10 col-lg-offset-1">
                                <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                      
                                        <tr>
                                            
                                            <th>Activity</th>
                                            <th>Description</th>
                                            <th>Start Date</th>
                                            <th>Region</th>
                                            <th>Division</th>
                                            <th>Date Entered</th>
                                            <th>PayPal ID</th>
                                        </tr>
                                        
                                    </thead>
                                    
                                    <tbody>
                                        <tr>
                                            <td colspan="7" align="center">
                                                You have not yet played any leagues. <a href="competition-league-sign.html">Why not to join next term's league ?</a>
                                            </td>
                                            
                                        </tr>
                          
                                        
                                    </tbody>
                               
                                 
                                 
                                 
                                </table>
                            </div>
                                
                                
                            </div>
                            
                            
  
                        </div>
                        
                        
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>