<div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>MY ACCOUNT</h1>
                      </div>
                      
                      
                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                                <?php echo $this->partial('application/my-account/partials/subnav.phtml');?>
                                
                                <hr>
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-lg-10 col-lg-offset-1">
                                <form class="form-horizontal new-forum" role="form">
                           
  <div class="form-group">
    <label for="player-name" class="col-lg-1 col-md-1 col-sm-2 control-label">Username</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" id="player-name" >
    </div>
    <div class="col-sm-3">
        <button type="submit" name="findcourt" class="btn btn-green">add player</button>  
        
    </div>
    
  </div>
                                      
                                      </form>
                              
                              
                               
 
                            </div>
                            
                            <div class="col-lg-10 col-lg-offset-1">
                                <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            
                                            <th>Username</th>
                                            <th>Won</th>
                                            <th>Lost</th>
                                            <th>Drawn</th>
                                            <th>Receive Match Results via Email ?</th>
                                            <th>Remove</th>
                                        </tr>
                                        
                                    </thead>
                                    
                                    <tbody>
                                        <tr>
                                            <td><a data-toggle="modal" data-target="#playermodal" href="#profile">Paul Barton</a></td>
                                            <td>0</td>
                                            <td>0</td>
                                            <td>0</td>
                                            <td align="center"><a href="#receiveresults">Yes</a></td>
                                            <td align="center"><a href="#remove"><img src="/img/close.png" alt=""></a></td>
                                            
                                            
                                        </tr>
                                        
                                        <tr>
                                            <td><a data-toggle="modal" data-target="#playermodal" href="#profile">Paul Barton</a></td>
                                            <td>0</td>
                                            <td>0</td>
                                            <td>0</td>
                                            <td align="center"><a href="#receiveresults">Yes</a></td>
                                            <td align="center"><a href="#remove"><img src="/img/close.png" alt=""></a></td>
                                            
                                            
                                        </tr>
                                        <tr>
                                            <td><a data-toggle="modal" data-target="#playermodal" href="#profile">Paul Barton</a></td>
                                            <td>0</td>
                                            <td>0</td>
                                            <td>0</td>
                                            <td align="center"><a href="#receiveresults">Yes</a></td>
                                            <td align="center"><a href="#remove"><img src="/img/close.png" alt=""></a></td>
                                            
                                            
                                        </tr>
                                        
                                        
                                    </tbody>
                               
                                 
                                 
                                 
                                </table>
                            </div>
                                
                                
                            </div>
                            
                            
  
                        </div>
                        
                        
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>