<div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>MY ACCOUNT</h1>
                      </div>
                      
                      
                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                                <?php echo $this->partial('application/my-account/partials/subnav.phtml');?>
                                <p class="subscribed"><span class="glyphicon glyphicon-ok"></span>Thank you. Message has been sent!</p>
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-lg-10 col-lg-offset-1">
                               <div class="col-lg-3 col-md-3 col-sm-3">
                                 
                                  <div class="panel panel-default inbox-panel">

                                  <?php echo $this->partial('application/my-account/partials/sidenav.phtml');?>

</div>
                                  
                           
                                   
                               </div>
                               
                               
                           
                               <div class="col-lg-9 col-md-9 col-sm-9">
                                                                   
                                 
  
  
<!--  Message   -->
  <div class="panel-group messages-accordion" id="accordion" role="tablist" aria-multiselectable="true">
  
  
  
  <!--  Message Panel Repeat   -->
<div class="panel panel-default new message">
  <div class="panel-heading" role="tab"  data-toggle="collapse" data-target="#message1">
      <h4 class="panel-title">Paul Barton </h4>
      <p>-  Welcome !</p>
      <span class="date">15 Jan '15 12:55</span>
  </div>
  <div class="panel-body message-body collapse  " id="message1">
   <div class="message-panel  ">
           
             <div class="message-full">
                <div class="message-header clearfix">
                    <div class="heading">
                
                                   <p>From :</p>
                                   <a href="#player-profile">Paul Barton</a>
                        
                    </div>
                       
                        <div class="heading">
                        
                    <p>Subject :</p>
                   <p> Welcome !</p>
                  
                    </div>
                       
                       <div class="heading">
                
                                  <p>Date:</p>
                                               <p>15 Jan '15 12:55</p>
                      
                    </div>
                        
               
                </div>
                  <hr/>
                <div >
                   Hi Casper! <br><br>
                    Welcome to your London Tennis Messages Section.
<br><br>
Here you you can check messages you have send or recieved by members of London Tennis community.
<br><br>
Why not take a read of the <a href="">getting started</a> page to get up to speed with the various parts of the London Tennis website.
                   
                </div>
                
               
             </div>
         
          
      
       
       
       
   </div>
     <button type="submit" id="button_profiletext" name="findplayerbutton" class="btn btn-green pull-right"><span class="glyphicon glyphicon-share-alt"></span>Reply</button> 
  </div>
      </div>
   <!-- End Message Panel   -->
   
     <!--  Message Panel Repeat   -->
<div class="panel panel-default message">
  <div class="panel-heading" role="tab"  data-toggle="collapse" data-target="#message2">
      <h4 class="panel-title">Paul Barton </h4>
      <p>-  Welcome !</p>
      <span class="date">15 Jan '15 12:55</span>
  </div>
  <div class="panel-body message-body collapse  " id="message2">
   <div class="message-panel  ">
           
             <div class="message-full">
                <div class="message-header clearfix">
                    <div class="heading">
                
                                   <p>From :</p>
                                   <a href="#player-profile">Paul Barton</a>
                        
                    </div>
                       
                        <div class="heading">
                        
                    <p>Subject :</p>
                   <p> Welcome !</p>
                  
                    </div>
                       
                       <div class="heading">
                
                                  <p>Date:</p>
                                               <p>15 Jan '15 12:55</p>
                      
                    </div>
                        
               
                </div>
                  <hr/>
                <div >
                   Hi Casper! <br><br>
                    Welcome to your London Tennis Messages Section.
<br><br>
Here you you can check messages you have send or recieved by members of London Tennis community.
<br><br>
Why not take a read of the <a href="">getting started</a> page to get up to speed with the various parts of the London Tennis website.
                   
                </div>
                
               
             </div>
         
          
      
       
       
       
   </div>
     <button type="submit" id="button_profiletext" name="findplayerbutton" class="btn btn-green pull-right"><span class="glyphicon glyphicon-share-alt"></span>Reply</button> 
  </div>
      </div>
   <!-- End Message Panel   -->
   
   
   
   
   <!--  Message Panel Repeat   -->
<div class="panel panel-default message">
  <div class="panel-heading" role="tab"  data-toggle="collapse" data-target="#message3">
      <h4 class="panel-title">Paul Barton </h4>
      <p>-  Welcome !</p>
      <span class="date">15 Jan '15 12:55</span>
  </div>
  <div class="panel-body message-body collapse  " id="message3">
   <div class="message-panel  ">
           
             <div class="message-full">
                <div class="message-header clearfix">
                    <div class="heading">
                
                                   <p>From :</p>
                                   <a href="#player-profile">Paul Barton</a>
                        
                    </div>
                       
                        <div class="heading">
                        
                    <p>Subject :</p>
                   <p> Welcome !</p>
                  
                    </div>
                       
                       <div class="heading">
                
                                  <p>Date:</p>
                                               <p>15 Jan '15 12:55</p>
                      
                    </div>
                        
               
                </div>
                  <hr/>
                <div >
                   Hi Casper! <br><br>
                    Welcome to your London Tennis Messages Section.
<br><br>
Here you you can check messages you have send or recieved by members of London Tennis community.
<br><br>
Why not take a read of the <a href="">getting started</a> page to get up to speed with the various parts of the London Tennis website.
                   
                </div>
                
               
             </div>
         
          
      
       
       
       
   </div>
     <button type="submit" id="button_profiletext" name="findplayerbutton" class="btn btn-green pull-right"><span class="glyphicon glyphicon-share-alt"></span>Reply</button> 
  </div>
      </div>
   <!-- End Message Panel   -->
   
  
  
  
  
  
  </div>
  


                                  
                                   
                               </div>
 
                            </div>
  
                        </div>
                        
                        
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>