<div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>MY ACCOUNT</h1>
                      </div>
                      
                      
                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                               <?php echo $this->partial('application/my-account/partials/subnav.phtml');?>
                                <hr>
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-lg-10 col-lg-offset-1">
                               <div class="col-lg-3 col-md-3 col-sm-3">
                                 
                                  <div class="panel panel-default inbox-panel">

 <?php echo $this->partial('application/my-account/partials/sidenav.phtml');?>
</div>
                                  
                           
                                   
                               </div>
                               
                               
                          
                               <div class="col-lg-9 col-md-9 col-sm-9">
                    
                    <div class="panel panel-default create-msg">
                       <div class="panel-body">
                          
<p class="small-text">                                                     If you arrange and play a match with another member of London Tennis, please consider entering your score on the results page.
<br><br>
If you play a league match, you must enter the score directly into the league table on the Leagues page in order for the score to be correctly associated with the league.</p>
                          <hr>
                           <form class="form-horizontal new-forum" role="form">
                           
                             <div class="form-group">
    <label for="player-name" class="col-sm-2 control-label">To</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="player-name" >
    </div>
  </div>

                           
  <div class="form-group">
    <label for="player-name" class="col-sm-2 control-label">Subject</label>
    <div class="col-sm-9">
      <input type="text" class="form-control" id="player-name" >
    </div>
  </div>
                                     
                                     <div class="form-group">
                                     
                                         <label for="" class=" col-sm-2 control-label">Message</label>
                                         <div class="col-sm-9">
                                             <textarea name="content" id="messagePost_id" class="form-control" cols="30" rows="10"></textarea>
                                             
                                                                                                  <p class="post-note">
Please consider taking time to respond to match requests received from other players even if you are unable to play!
<br><br>
Please refrain from sending any messages that may be considered abusive by the recipient. Failing to do so may result in the termination of your account.
</p>
                                         </div>
                                         
                                     </div>
                                      
<div class="submit">
   <button type="submit" name="findplayerbutton" class="btn btn-green pull-right"><span class="glyphicon glyphicon-share-alt"></span>Send</button>  
    
</div>
                                      
                                      </form>
                           
                           
                           
                       </div>
                        
                        
                        
                    </div>
  
  
  


                                  
                                   
                               </div>
 
                            </div>
  
                        </div>
                        
                        
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>
       