
        <!-- Home page content  -->

         <div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      
                      <div class="paper-content homepage">
                      
                      <div class="home-section row ">
                          <div class="col-lg-12 col1 col-md-12 wow fadeInLeft ">
                              <div class="home-text">
                                  <h2>LONDON TENNIS</h2>
                                  <p class="col-lg-8 col-lg-offset-2">A community of over 16000 tennis players who have recorded thousands of match results at hundreds of venues in the last 12 months. Find opponents, schedule matches, record results and get a site ranking, all completely free of charge, join now and find your match!</p>
                                  
                              </div>
                              
                          </div>
                          
                                        
                                                 
                      </div>
                      
                      <hr>
                      
                      <div class="home-section row">
                         <div class="col-lg-6 col1 col-md-6  wow fadeInLeft">
                           <div class="home-text">
                                 <h2>COMPETE</h2>
                             <p>Arrange friendly matches and join our triannual knockout competition and get FREE British Tennis membership. Currently we offer Men's and Ladies' singles events with the finals played at The National Tennis Centre, Roehampton. There are great trophies and prize money for the winners and runners-up, including a consolation rounds in both events. <a href="competition-ko-sign.html">Read More</a></p>
                               
                           </div>
                             
                             
                         </div>
                         
                         <div class="col-lg-6 col1 col-md-6 col-sm-12 wow fadeInRight" data-wow-delay="300ms">
                            <div class="img-wrap">
                                 <img src="/img/compete.png" alt="">
                                
                            </div>
                             
                         </div>
                          
                          
                      </div>
                      
                      
                      <div class="home-section row">
                         <div class="col-lg-6 col2 col-md-6  wow fadeInRight">
                           <div class="home-text">
                                 <h2>FIND A PARTNER</h2>
                             <p>We have been helping players find one other for social and competitive tennis for over ten years. Almost 40000 match scores have been recorded altogether, helping players to receive a site ranking and to find players of a similar level in their locality.</p>
                               
                           </div>
                             
                             
                         </div>
                         
                         <div class="col-lg-6 col2 col-md-6 col-sm-12 wow fadeInLeft" data-wow-delay="300ms">
                              <div class="img-wrap">
                                 <img src="/img/search.png" alt="">
                                
                            </div>
                             
                         </div>
                          
                          
                      </div>
                      
<hr>
                      <div class="home-section row  ">
                          <div class="col-lg-6 col1 col-md-6 wow fadeInLeft">
                              <div class="home-text">
                                  <h2>INTERACTIVE MAP</h2>
                                  <p>Our new improved map will allow you to find your nearest clubs and parks, so that you can arrange matches with players in your area.</p>
                                  
                              </div>
                              
                          </div>
                          
                        <div class="col-lg-6 col2 col-md-6 col-sm-12  wow fadeInRight" data-wow-delay="300ms">
                             <div class="img-wrap">
                                 <img src="/img/map2.png" alt="">
                                
                            </div>
                            
                        </div>                           
                                                 
                      </div>
                      <hr>
                      
                      <div class="home-section row">
                         <div class="col-lg-6 col2 col-md-6  wow fadeInRight">
                           <div class="home-text">
                                 <h2>DIRECTORIES</h2>
                             <p>Find all of your other tennis needs from coaching to physiotherapy, in our excellent London Tennis Trade listings.<a href="competition-ko-sign.html">Read More</a></p>
                               
                           </div>
                             
                             
                         </div>
                         
                         <div class="col-lg-6 col2 col-md-6 col-sm-12 wow fadeInLeft" data-wow-delay="300ms">
                              <div class="img-wrap">
                                 <img src="/img/directories.png" alt="">
                                
                            </div>
                             
                         </div>
                          
                          
                      </div>
                       
                       
                        
                        
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>
       
  <div class="home-seemore clearfix">
    <div class="join-text">
          <a class="btn btn-lg join-button " href="join-page.html" role="button">BE A PART OF LONDON TENNIS !</a>
            <p>FIND OUT MORE AND READ OUR <a href="">"GETTING STARTED"</a> PAGE</p>
    </div>
    
     <div class="section-img-wrap">
         
     </div>
      
      
  </div>
  
  <script>
        $(document).ready(function(){
             if(Modernizr.touch){
                }else{       
                    new WOW().init();
                    
                }
            
        });
        
        
        </script>