<div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>MY ACCOUNT</h1>
                      </div>
                      
                      
                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                            
                                 <?php echo $this->partial('application/courts/partials/subnav.phtml'); ?>
                                
                                <hr>
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-lg-10 col-lg-offset-1">
                               
                              Please use the <a href="courts-search.html">Find a Court</a> database to locate a court and then click Add to Favourites to select a court as one of your favourites.

If you cannot find a court in the database, please <a href="help-page.html">let us know</a> the details and we will add the court to the database.
                               
 <hr>
                            </div>
                            
                            <div class="col-lg-10 col-lg-offset-1">
                                <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            
                                            <th>Court Name</th>
                                             <th>Home Venue</th>
                                            <th>Remove</th>
                                        </tr>
                                        
                                    </thead>
                                    
                                    <tbody>
                                        <tr>
                                            <td><a href="#courtpage">Wimbledon Park</a></td>
                                           <td><a  href="#makehome">Make Home Venue</a></td>
                                            <td ><a href="#remove"><img src="/img/close.png" alt=""></a></td>
                                            
                                            
                                        </tr>
                                        
                                        <tr>
                                            <td><a href="#courtpage">Wimbledon Park</a></td>
                                           <td><a  href="#makehome">Make Home Venue</a></td>
                                            <td ><a href="#remove"><img src="/img/close.png" alt=""></a></td>
                                            
                                            
                                        </tr>
                                        
                                        <tr>
                                            <td><a href="#courtpage">Wimbledon Park</a></td>
                                           <td><a  href="#makehome">Make Home Venue</a></td>
                                            <td ><a href="#remove"><img src="/img/close.png" alt=""></a></td>
                                            
                                            
                                        </tr>
                                        
                                        
                                        
                                      
                                        
                                        
                                        
                                        
                                    </tbody>
                               
                                 
                                 
                                 
                                </table>
                            </div>
                                
                                
                            </div>
                            
                            
  
                        </div>
                        
                        
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>