<div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>COURTS</h1>
                      </div>
                      
                      
                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">

                            
                            <?php echo $this->partial('application/courts/partials/subnav.phtml'); ?>
                            
                                
                                <p class="description">If entering text below, auto-suggestions will be given based on club name only and are limited to 25 selections. The suggestions are in order of court popularity and do not take account of the other information on this form such as the postcode area. If your court does not appear, please use the Full Search button to do a detailed search of the database which will also search for addresses.</p>
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-lg-10 col-lg-offset-1 col-sm-10 col-sm-offset-1 ">
                                <form class="form-horizontal" role="form">
  <div class="form-group">
    <label for="player-name" class="col-sm-2 control-label">Part of name or addres</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="player-name" placeholder="eg. Wimbledon Park">
    </div>
    <div class="col-sm-3">
        <button type="submit" name="findcourt" class="btn btn-green">FULL SEARCH</button>  
        
    </div>
    
  </div>
  
  <div class="form-group">
   <span  class="help-block ">Please enter the region you would like to play - please only enter the first part of the postcode, e.g. SW6</span>
    <label class="col-sm-2 control-label">Within</label>
    <div class="col-sm-10">
     
      <input type="text" class="form-control" id="player-within-miles" placeholder="eg.4">
      <label class="control-label within-miles">Miles of Postcode</label>
      <input type="text" class="form-control" id="player-within-postcode" placeholder="eg.SW6">
      
    </div>
  </div>
  
   <div class="form-group">
   
    <label  class="col-sm-2 control-label">Park or club</label>
    <div class="col-sm-10">
     
<select name="parkratingfrom" class="form-control court-find">
     <option value="0">Either</option>
     <option value="1">Park</option>
     <option value="2">Club</option>
    </select>
     
      
    </div>
  </div>
  
   <div class="form-group">
   
    <label  class="col-sm-2 control-label">Free to play</label>
    <div class="col-sm-10">
     
<select name="parkratingfrom" class="form-control court-find">
     <option value="0">Don't Mind</option>
     <option value="1">Free to Play</option>
     
    </select>
     
      
    </div>
  </div>
  
  <div class="form-group">
   
    <label  class="col-sm-2 control-label">Court type</label>
    <div class="col-sm-10">
     
<select name="parkratingfrom" class="form-control court-find">
     <option value="0">Don't Mind</option>
     <option value="1">Indoor</option>
     <option value="2">Floodlit</option>
     <option value="3">Clay</option>
     <option value="4">Grass</option>
     <option value="5">Hard/Other</option>
     
     
    </select>
     
      
    </div>
  </div>
  
    
  
  
  <div class="form-group">
     <span  class="help-block ">Please keep us up-to-date with any knowledge you have about courts that is not accurately represented in the database.</span> 
   
  
  </div>
  
    
  


</form>
                              
                              
                               
                                
                            </div>
                            
                            
                            
                            
                            
                        </div>
                        
                        
                        
                        
                        
                        
                        
                    <!-- Interactive Map , swap for courts-results to display results   -->  
                        
                        
                        <div class="row map-section">
                            <div class="col-lg-12">
                               
                                 <div class="title">
                          <h1>LONDON COURT MAP</h1>
                          
                      </div>
                             
                              <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                                <div class="filters">
                                      <ul class="nav-tabs nav">
                                      <li class="active"><a href="#search-players">All Courts</a></li>
                                      <li ><a href="#most-played">Free Parks</a></li>
                                      <li ><a href="#most-wins">Pay-to-play</a></li>
                                      <li ><a href="#most-wins">Clubs</a></li>
                                

                                       </ul>
                                </div>
                                
                                <p class="description">  The map below shows the known, London-based, courts. The size of the marker indicates the number of matches played. Hover over a court for more details and click to go to that venue's page.</p>
                            </div>
                             
                                                           
                               
                                
                                
                                
                            </div>
                            
                            
                        </div>
                        
                        <div class="row map-section">
                            <div class="col-lg-12">
                              
                              
                          
                               <div class="map">
                                      <div class="court-tip">
                                      <a href="court-page.html">Wimbledon Park</a>
                                      <dl>
                                          <dt>Number of Courts</dt>
                                          <dd>3</dd>
                                          <dt>Postcode Area</dt>
                                          <dd>SW15 3ER</dd>
                                          <dt>Matches Played</dt>
                                          <dd>122</dd>
                                          
                                      </dl>
                                      
                                  </div>
                                  
                                  
                                  
                                   <img src="img/map.png" alt="">
                                   
                                   <div class="markers">
                                   <a style="left:100px;top:220px;" href="" class="pay marker sm"></a>
                                   <a style="left:200px;top:80px;" href="" class="pay marker md"></a>
                                   <a style="left:400px;top:280px;" href="" class="pay marker lg"></a>
                                   
                                    <a style="left:120px;top:120px;" href="" class="free marker sm"></a>
                                   <a style="left:400px;top:380px;" href="" class="free marke md"></a>
                                   <a style="left:40px;top:260px;" href="" class="free marker lg"></a>
                                   
                                    <a style="left:500px;top:120px;" href="" class="clubs marker sm"></a>
                                   <a style="left:270px;top:180px;" href="" class="clubs marker md"></a>
                                   <a style="left:300px;top:310px;" href="" class="clubs marker lg"></a>
                                   
                               </div>
                                  
                                  
                                   
                              
                               </div>
                               
                               
                               
                               
                               
                               
                               
                               
                               <div class="legend">
                                   <ul>
                                       <li>Pay-to-play</li>
                                       <li>Free Parks</li>
                                       <li>Clubs</li>
                                   </ul>
                                   
                               </div>
                                
                                
                                
                            </div>
                            
                            
                            
                            
                        </div>
                        
                      <!-- end of the map   -->
                        
                        
                        
                        
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>