<div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>FIND PLAYERS</h1>
                      </div>
                      
                      
                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                                <div class="filters">
                                      <ul class="nav-tabs nav">
                                      <li class="active"><a href="players.html">Search Players</a></li>
                                      <li ><a href="players-results.html">Most Played</a></li>
                                      <li ><a href="players-results.html">Most Wins</a></li>
                                      <li ><a href="players-results.html">Recently Played</a></li>
                                      <li ><a href="players-results.html">Currently Played</a></li>
                                      <li ><a href="players-results.html">Top Ranked</a></li>
                                      <li ><a href="players-results.html">Recent Joiners</a></li>

                                       </ul>
                                </div>
                                
                                <p class="description">This service is designed for you to be able to find a player in an area near you who is free and willing to play.
The more criteria you use, the narrower the search results will be. If you obtain no results, try reducing the number of criteria that you use.</p>
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-lg-10 col-lg-offset-1 col-sm-10 col-sm-offset-1 ">
                                <form class="form-horizontal" role="form">
  <div class="form-group">
    <label for="player-name" class="col-sm-2 control-label">All or part of name</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="player-name" placeholder="eg. Rob, Rob Jones">
    </div>
  </div>
  
  <div class="form-group">
   <span  class="help-block ">Please enter the region you would like to play - please only enter the first part of the postcode, e.g. SW6</span>
    <label class="col-sm-2 control-label">Within</label>
    <div class="col-sm-10">
     
      <input type="text" class="form-control" id="player-within-miles" placeholder="eg.4">
      <label class="control-label within-miles">Miles of Postcode</label>
      <input type="text" class="form-control" id="player-within-postcode" placeholder="eg.SW6">
      
    </div>
  </div>
  
   <div class="form-group">
   <span class="help-block ">Please select the skill level of the player you wish to find. Either select a park rating range, or an LTA rating range.</span>
    <label  class="col-sm-2 control-label">Park Rating</label>
    <div class="col-sm-10">
     
<select name="parkratingfrom" class="form-control park-rating">
     <option value="0">Any</option>
     <option value="1">ITN 1 - World Standard</option>
     <option value="2">ITN 2 - National Standard</option>
     <option value="3">ITN 3 - County Standard</option>
     <option value="4">ITN 4 - Top Club Level</option>
     <option value="5">ITN 5 - High Intermediate</option>
     <option value="6">ITN 6 - Middle Intermediate</option>
     <option value="7">ITN 7 - Low Intermediate</option>
     <option value="8">ITN 8 - Good Recreational</option>
     <option value="9">ITN 9 - Recreational</option></select>
      <label  class="control-label rating-label">to</label>
      <select name="parkratingto" class="form-control park-rating">
     <option value="0">Any</option>
     <option value="1">ITN 1 - World Standard</option>
     <option value="2">ITN 2 - National Standard</option>
     <option value="3">ITN 3 - County Standard</option>
     <option value="4">ITN 4 - Top Club Level</option>
     <option value="5">ITN 5 - High Intermediate</option>
     <option value="6">ITN 6 - Middle Intermediate</option>
     <option value="7">ITN 7 - Low Intermediate</option>
     <option value="8">ITN 8 - Good Recreational</option>
     <option value="9">ITN 9 - Recreational</option></select>
      
    </div>
  </div>
  
     <div class="form-group">
   
    <label class="col-sm-2 control-label">LTA Rating</label>
    <div class="col-sm-10">
     
<select name="ltaratingfrom" class="form-control park-rating">
     <option value="0">Any</option>
     <option value="10.2">10.2</option>
     <option value="10.1">10.1</option>
     <option value="9.2">9.2</option>
     <option value="9.1">9.1</option>
     <option value="8.2">8.2</option>
     <option value="8.1">8.1</option>
     <option value="7.2">7.2</option>
     <option value="7.1">7.1</option>
     <option value="6.2">6.2</option>
     <option value="6.1">6.1</option>
     <option value="5.2">5.2</option>
     <option value="5.1">5.1</option>
     <option value="4.2">4.2</option>
     <option value="4.1">4.1</option>
     <option value="3.2">3.2</option>
     <option value="3.1">3.1</option>
     <option value="2.2">2.2</option>
     <option value="2.1">2.1</option>
     <option value="1.2">1.2</option>
     <option value="1.1">1.1</option>
     </select>
     
      <label  class="control-label rating-label">to</label>
     <select name="ltaratingto" class="form-control park-rating">
     <option value="0">Any</option>
     <option value="10.2">10.2</option>
     <option value="10.1">10.1</option>
     <option value="9.2">9.2</option>
     <option value="9.1">9.1</option>
     <option value="8.2">8.2</option>
     <option value="8.1">8.1</option>
     <option value="7.2">7.2</option>
     <option value="7.1">7.1</option>
     <option value="6.2">6.2</option>
     <option value="6.1">6.1</option>
     <option value="5.2">5.2</option>
     <option value="5.1">5.1</option>
     <option value="4.2">4.2</option>
     <option value="4.1">4.1</option>
     <option value="3.2">3.2</option>
     <option value="3.1">3.1</option>
     <option value="2.2">2.2</option>
     <option value="2.1">2.1</option>
     <option value="1.2">1.2</option>
     <option value="1.1">1.1</option>
     </select>
      
    </div>
  </div>
  
  
  <div class="form-group">
     <span  class="help-block ">Please enter the region you would like to play - please only enter the first part of the postcode, e.g. SW6</span> 
    <label class="col-sm-2 control-label">Profile Required</label>
    <div class="col-sm-10">     
        <div class="checkbox">
        <label>
          <input type="checkbox">
        </label>
      </div>
    </div>
  </div>
  
    <div class="form-group">
     <span  class="help-block ">Please select one or more entries from the list below to specify the availability of the player you are looking for.</span> 
    <label class="col-sm-2 control-label">Availability</label>
    <div class="col-sm-10 availability">     
       <div class="radio">
  <label>
    <input type="checkbox" name="optionsRadios" id="optionsRadios1" value="any" checked>
    Any
  </label>
  
</div>
  <div class="radio ">
  <label>
    <input type="checkbox" name="optionsRadios" id="optionsRadios1" value="saturday" checked>
    Saturday
  </label>
  
</div>
   <div class="radio">
  <label>
    <input type="checkbox" name="optionsRadios" id="optionsRadios1" value="weekday-morning" checked>
    Weekday Morning
  </label>
  
</div>
   <div class="radio ">
  <label>
    <input type="checkbox" name="optionsRadios" id="optionsRadios1" value="sunday" checked>
    Sunday
  </label>
  
</div>
  
  
   <div class="radio">
  <label>
    <input type="checkbox" name="optionsRadios" id="optionsRadios1" value="weekday-afternoon" checked>
    Weekday Afternoon
  </label>
  
</div>
    <div class="radio ">
  <label>
    <input type="checkbox" name="optionsRadios" id="optionsRadios1" value="short-notice" checked>
    Short Notice
  </label>
  
</div>
  
   <div class="radio">
  <label>
    <input type="checkbox" name="optionsRadios" id="optionsRadios1" value="weekday-evening" checked>
    Weekday Evening
  </label>
  
</div>
  
  
   <div class="radio ">
  <label>
    <input type="checkbox" name="optionsRadios" id="optionsRadios1" value="school-holiday" checked>
    School Holiday
  </label>
  
</div>
    </div>
  </div>
  
<div class="submit col-lg-2 ">
   <button type="submit" name="findplayerbutton" class="btn btn-green">Find Player</button>  
    
</div>

</form>
                                
                            </div>
                            
                            
                        </div>
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>