<div class="row">

	<div class="col-lg-12 ">

		<div class="box-profile-details clearfix">
			<div class="col-lg-3 col-sm-3 ">
				<span class="img-thumb"> <img src="<?php echo $this->player['profileImage']; ?>" alt="">
				</span>
			</div>

			<div class="col-lg-9 profile-bubble col-sm-9">
				<div class="box-about-details">
					<p><?php echo $this->player['profileText']; ?></p>
				</div>

				<div class="links">
					<a class="btn btn-green" href="my-account-inbox.html">Send Message</a>
					<a class="btn btn-green" href="<?php echo $this->url('players/profile', ['playerid' => $this->player['id']]) ?>">View Full profile</a>

				</div>
			</div>

		</div>
		<hr />
		<div class="box-player-stats clearfix">

			<div class="col-lg-6">
				<?php echo $this->partial('application/players/partials/player-details-table.phtml'); ?>

			</div>

			<div class="col-lg-6">
				<?php echo $this->partial('application/players/partials/tennis-preferences-table.phtml'); ?>

			</div>


		</div>


		<div class="box-player-stats clearfix">

			<div class="col-lg-6">
				<?php echo $this->partial('application/players/partials/performance-table.phtml'); ?>
			</div>

			<div class="col-lg-6">
				<?php echo $this->partial('application/players/partials/history-table.phtml'); ?>
			</div>


		</div>

		<div class="box-profile-notes">
			<p>* A player has a rating if he or she has played at least five
				unique opponents and at least one match in the past twelve months.
				There are currently 500 ranked players. More points will be awarded
				for beating better players. Ratings are updated daily.</p>

		</div>

	</div>

</div>
