<div class="container paper">
	<div class="shadow"></div>
	<div class="row">
		<div class="col-lg-12">
			<div class="content">
				<div class="title">
					<h1>FIND PLAYERS</h1>
				</div>



				<div class="paper-content player-profile ">
					<div class="row">
						<div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
							<?php echo $this->partial('application/players/partials/subnav.phtml');?>
							<p class="venue-title"><?php echo $this->player['name']; ?></p>
						</div>

					</div>

					<div class="row">





						<div class="col-lg-10 col-lg-offset-1">

							<div class="box-profile-details clearfix">
								<div class="col-lg-3 col-sm-3 ">
									<span class="img-thumb center-block"> 
									<img src="<?php echo $this->player['profileImage']; ?>" alt="">
									</span>

								</div>

								<div class="col-lg-9 profile-bubble col-sm-9  ">
									<div class="box-about-details">
										<p><?php echo $this->player['profileText']; ?></p>

									</div>

									<div class="links">
										<a class="btn btn-green" href="my-account-inbox.html">Send
											Message</a> <a class="btn btn-green" href="my-account-inbox.html">View
											messages</a>


									</div>
								</div>

							</div>
						</div>







						<div class="col-lg-10 col-lg-offset-1">








							<hr>
							<div class="box-player-stats clearfix">

								<div class="col-lg-3">
									<table class="table box-stats-table table-bordered">
										<thead>
											<tr>
												<td colspan="2">
													<p class="text-center">Player Details</p>
												</td>
											</tr>

										</thead>

										<tbody>
											<tr>
												<td>Name</td>
												<td><?php echo $this->player['name']; ?></td>
											</tr>

											<tr>
												<td>Gender</td>
												<td><?php echo $this->player['sex']; ?></td>
											</tr>
											<tr>
												<td>Joined</td>
												<td><?php echo $this->player['joinDate']; ?></td>
											</tr>
											<tr>
												<td>User Rating</td>
												<td><?php echo $this->player['userRating']; ?></td>
											</tr>
											<tr>
												<td>LTA Number</td>
												<td><?php echo $this->player['ltaNumber']; ?></td>
											</tr>
											<tr>
												<td>LTa Rating</td>
												<td><?php echo $this->player['ltaRating']; ?></td>
											</tr>


										</tbody>


									</table>

								</div>

								<div class="col-lg-3">
									<table class="table box-stats-table table-bordered">
										<thead>
											<tr>
												<td colspan="2">
													<p class="text-center">Tennis Preferences</p>
												</td>
											</tr>

										</thead>

										<tbody>
											<tr>
												<td>Play Radius</td>
												<td><?php echo $this->player['milesRadius']; ?></td>
											</tr>

											<tr>
												<td>Opponents</td>
												<td><?php echo $this->player['opponentSex']; ?></td>
											</tr>
											<tr>
												<td>Format</td>
												<td><?php echo $this->player['format']; ?></td>
											</tr>
											<tr>
												<td>Times</td>
												<td><?php echo $this->player['availability']; ?></td>
											</tr>
											<tr>
												<td>Home Venue</td>
												<td>Wimbledon Park</td>
											</tr>



										</tbody>


									</table>

								</div>


								<div class="col-lg-3">
									<table class="table box-stats-table table-bordered">
										<thead>
											<tr>
												<td colspan="2">
													<p class="text-center">Performance</p>
												</td>
											</tr>

										</thead>

										<tbody>
											<tr>
												<td>Rank</td>
												<td>Unrated *</td>
											</tr>

											<tr>
												<td>Points</td>
												<td>Unrated</td>
											</tr>
											<tr>
												<td>Percentile</td>
												<td>Unrated</td>
											</tr>
											<tr>
												<td>W/L/D</td>
												<td>15/4/1</td>
											</tr>



										</tbody>


									</table>

								</div>

								<div class="col-lg-3">
									<table class="table box-stats-table table-bordered">
										<thead>
											<tr>
												<td colspan="2">
													<p class="text-center">Playing History</p>
												</td>
											</tr>

										</thead>

										<tbody>
											<tr>
												<td>Last Played</td>
												<td>09 Jan '14</td>
											</tr>

											<tr>
												<td>Unique Opponents</td>
												<td>9</td>
											</tr>
											<tr>
												<td>Unique Venues</td>
												<td>4</td>
											</tr>
											<tr>
												<td>Friendly Matches</td>
												<td>20</td>
											</tr>
											<tr>
												<td>League Matches</td>
												<td>2</td>
											</tr>
											<tr>
												<td>Knockout Matches</td>
												<td>1</td>
											</tr>


										</tbody>


									</table>

								</div>


							</div>


							<hr>

							<div class="division-name">
								<p>
									Availability Calendar <a href="#results">View Full Calendar</a>
								</p>

							</div>
							<div class="table-responsive">
								<table class="table table-striped">
									<thead>


										<tr>

											<th>Date</th>
											<th class="text-center">Morning</th>
											<th class="text-center">Afternoon</th>
											<th class="text-center">Evening</th>
											<th>Match Type</th>

										</tr>

									</thead>

									<tbody>
										<tr>
											<td>Fri 16th Jan 2015</td>
											<td align="center">&check;</td>
											<td align="center">&check;</td>
											<td align="center">&check;</td>

											<td>Double</td>



										</tr>

										<tr class="weekend">
											<td>Sat 17th Jan 2015</td>
											<td align="center">&check;</td>
											<td align="center">&check;</td>
											<td align="center">&check;</td>

											<td>Single</td>



										</tr>

										<tr class="weekend">
											<td>Sun 18th Jan 2015</td>
											<td align="center">&check;</td>
											<td align="center">&check;</td>
											<td align="center">&check;</td>

											<td>Double</td>




										</tr>

										<tr>
											<td>Mon 19th Jan 2015</td>
											<td align="center">&check;</td>
											<td align="center">&check;</td>
											<td align="center">&check;</td>

											<td>Single</td>




										</tr>


									</tbody>




								</table>
							</div>

							<hr>


							<div class="division-name">
								<p>
									Recent results for Paul <a href="#results">View all matches</a>
								</p>

							</div>
							<div class="table-responsive">
								<table class="table table-striped">
									<thead>



										<tr>
											<th>Date</th>
											<th>Player 1</th>
											<th>Player 2</th>
											<th>Score</th>
											<th>Type</th>
											<th>Venue</th>



										</tr>

									</thead>

									<tbody>
										<tr>
											<td>14 Dev '14</td>
											<td><a href="#player-1">dmitri79</a></td>
											<td><a href="#player-2">yanis_a</a></td>
											<td>6-4 6-4 7-5 5-2</td>
											<td>Friendly</td>
											<td><a href="#venue">Southfields Recreation Ground</a></td>


										</tr>

										<tr>
											<td>14 Dev '14</td>
											<td><a href="#player-1">dmitri79</a></td>
											<td><a href="#player-2">yanis_a</a></td>
											<td>6-4 6-4 7-5 5-2</td>
											<td>Friendly</td>
											<td><a href="#venue">Southfields Recreation Ground</a></td>


										</tr>

										<tr>
											<td>14 Dev '14</td>
											<td><a href="#player-1">dmitri79</a></td>
											<td><a href="#player-2">yanis_a</a></td>
											<td>6-4 6-4 7-5 5-2</td>
											<td>Friendly</td>
											<td><a href="#venue">Southfields Recreation Ground</a></td>


										</tr>

										<tr>
											<td>14 Dev '14</td>
											<td><a href="#player-1">dmitri79</a></td>
											<td><a href="#player-2">yanis_a</a></td>
											<td>6-4 6-4 7-5 5-2</td>
											<td>Friendly</td>
											<td><a href="#venue">Southfields Recreation Ground</a></td>


										</tr>

										<tr>
											<td>14 Dev '14</td>
											<td><a href="#player-1">dmitri79</a></td>
											<td><a href="#player-2">yanis_a</a></td>
											<td>6-4 6-4 7-5 5-2</td>
											<td>Friendly</td>
											<td><a href="#venue">Southfields Recreation Ground</a></td>


										</tr>

										<tr>
											<td>14 Dev '14</td>
											<td><a href="#player-1">dmitri79</a></td>
											<td><a href="#player-2">yanis_a</a></td>
											<td>6-4 6-4 7-5 5-2</td>
											<td>Friendly</td>
											<td><a href="#venue">Southfields Recreation Ground</a></td>


										</tr>



									</tbody>




								</table>
							</div>

							<hr>


							<div class="division-name">
								<p>Your recent results against Paul</p>

							</div>
							<div class="table-responsive">
								<table class="table table-striped">
									<thead>
										<tr>
											<th>Date</th>
											<th>Player 1</th>
											<th>Player 2</th>
											<th>Score</th>
											<th>Type</th>
											<th>Venue</th>
										</tr>

									</thead>

									<tbody>
										<tr>
											<td colspan="6" class="text-center">You have not
												recorded any matches with this player</td>



										</tr>


									</tbody>




								</table>
							</div>


							<hr>


							<div class="col-lg-6 col-sm-6">
								<div class="division-name">
									<p>Tournaments</p>

								</div>
								<div class="table-responsive">
									<table class="table table-striped">


										<tbody>
											<tr>
												<td><a href="#leagues">Summer 2011 South West
														London Men/Mixed Div 3</a></td>
											</tr>

											<tr>
												<td><a href="#leagues">Summer 2011 South West
														London Men/Mixed Div 3</a></td>
											</tr>

											<tr>
												<td><a href="#leagues">Summer 2011 South West
														London Men/Mixed Div 3</a></td>
											</tr>




										</tbody>




									</table>
								</div>
							</div>




							<div class="col-lg-6 col-sm-6">
								<div class="division-name">
									<p>Favourite Courts</p>

								</div>
								<div class="table-responsive">
									<table class="table table-striped">


										<tbody>
											<tr>
												<td><a href="/findcourt/courtdetails.php?courtid=845">Wimbledon
														Park</a></td>
											</tr>

											<tr>
												<td><a href="/findcourt/courtdetails.php?courtid=845">Wimbledon
														Park</a></td>
											</tr>

											<tr>
												<td><a href="/findcourt/courtdetails.php?courtid=845">Wimbledon
														Park</a></td>
											</tr>




										</tbody>




									</table>
								</div>


							</div>

							<hr>

						</div>


					</div>


				</div>

			</div>

		</div>

	</div>

</div>