<div class="container paper">
	<div class="shadow"></div>
	<div class="row">
		<div class="col-lg-12">
			<div class="content">
				<div class="title">
					<h1>FIND PLAYERS</h1>
				</div>



				<div class="paper-content player-profile ">
					<div class="row">
						<div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
							<?php echo $this->partial('application/players/partials/subnav.phtml');?>
							<p class="venue-title"><?php echo $this->player['name']; ?></p>
						</div>

					</div>
					<div class="row">

						<div class="col-lg-10 col-lg-offset-1">

							<div class="box-profile-details clearfix">
								<div class="col-lg-3 col-sm-3 ">
									<span class="img-thumb center-block"> 
									<img src="<?php echo $this->player['profileImage']; ?>" alt="">
									</span>

								</div>

								<div class="col-lg-9 profile-bubble col-sm-9  ">
									<div class="box-about-details">
										<p><?php echo $this->player['profileText']; ?></p>

									</div>

									<div class="links">
										<a class="btn btn-green" href="my-account-inbox.html">Send
											Message</a> <a class="btn btn-green" href="my-account-inbox.html">View
											messages</a>


									</div>
								</div>

							</div>
						</div>


						<div class="col-lg-10 col-lg-offset-1">
							<hr>
							<div class="box-player-stats clearfix">

								<div class="col-lg-3">
									<?php echo $this->partial('application/players/partials/player-details-table.phtml'); ?>

								</div>

								<div class="col-lg-3">
								    <?php echo $this->partial('application/players/partials/tennis-preferences-table.phtml'); ?>
								
									
								</div>


								<div class="col-lg-3">
								    <?php echo $this->partial('application/players/partials/performance-table.phtml'); ?>
								
									

								</div>

								<div class="col-lg-3">
									<?php echo $this->partial('application/players/partials/history-table.phtml'); ?>

								</div>


							</div>

							<hr>

							<div class="division-name">
								<p>
									Availability Calendar <a href="#results">View Full Calendar</a>
								</p>

							</div>
							<?php echo $this->partial('application/players/partials/calendar.phtml'); ?>

							<hr>


							<div class="division-name">
								<p>
									Recent results for <?= $this->player['name']; ?> <a href="#results">View all matches</a>
								</p>

							</div>
							<?php echo $this->partial('application/players/partials/results-table.phtml', ['resultList' => $this->results]); ?>

							<hr>


							<div class="division-name">
								<p>Your recent results against <?= $this->player['name']; ?></p>

							</div>
							<?php echo $this->partial('application/players/partials/results-table.phtml', ['resultList' => $this->resultsAgainstYou]); ?>

							<hr>


							<div class="col-lg-6 col-sm-6">
								<div class="division-name">
									<p>Tournaments</p>

								</div>
								<div class="table-responsive">
									<table class="table table-striped">


										<tbody>
											<tr>
												<td><a href="#leagues">Summer 2011 South West
														London Men/Mixed Div 3</a></td>
											</tr>

											<tr>
												<td><a href="#leagues">Summer 2011 South West
														London Men/Mixed Div 3</a></td>
											</tr>

											<tr>
												<td><a href="#leagues">Summer 2011 South West
														London Men/Mixed Div 3</a></td>
											</tr>




										</tbody>




									</table>
								</div>
							</div>




							<div class="col-lg-6 col-sm-6">
								<div class="division-name">
									<p>Favourite Courts</p>

								</div>
								<div class="table-responsive">
									<table class="table table-striped">


										<tbody>
											<tr>
												<td><a href="/findcourt/courtdetails.php?courtid=845">Wimbledon
														Park</a></td>
											</tr>

											<tr>
												<td><a href="/findcourt/courtdetails.php?courtid=845">Wimbledon
														Park</a></td>
											</tr>

											<tr>
												<td><a href="/findcourt/courtdetails.php?courtid=845">Wimbledon
														Park</a></td>
											</tr>




										</tbody>




									</table>
								</div>


							</div>

							<hr>

						</div>


					</div>


				</div>

			</div>

		</div>

	</div>

</div>