<div class="modal fade" id="playermodal" tabindex="-1" role="dialog" aria-labelledby="profilemodal" aria-hidden="false">
	<div class="modal-backdrop fade in" style="height: 1056px;"></div>
	<div class="modal-dialog modal-dm">
		<div class="modal-content">
		
		
		<div class="modal-header">

          <p class="box-profile-title"></p>
          <a href="" data-dismiss="modal"><img src="/img/close.png" alt=""></a>
     </div>
     
     

			<div class="modal-body"></div>
		</div>
	</div>
</div>
