<table class="table box-stats-table table-bordered">
										<thead>
											<tr>
												<td colspan="2">
													<p class="text-center">Playing History</p>
												</td>
											</tr>

										</thead>

										<tbody>
											<tr>
												<td>Last Played</td>
												<td><?php echo $this->player['lastPlayedTime']; ?></td>
											</tr>

											<tr>
												<td>Unique Opponents</td>
												<td><?php echo $this->player['uniqueOpponents']; ?></td>
											</tr>
											<tr>
												<td>Unique Venues</td>
												<td><?php echo $this->player['uniqueVenues']; ?></td>
											</tr>
											<tr>
												<td>Friendly Matches</td>
												<td><?php echo $this->player['friendlyMatches']; ?></td>
											</tr>
											<tr>
												<td>League Matches</td>
												<td><?php echo $this->player['leagueMatches']; ?></td>
											</tr>
											<tr>
												<td>Knockout Matches</td>
												<td><?php echo $this->player['knockoutMatches']; ?></td>
											</tr>


										</tbody>


									</table>