<table class="table box-stats-table table-bordered">
										<thead>
											<tr>
												<td colspan="2">
													<p class="text-center">Playing History</p>
												</td>
											</tr>

										</thead>

										<tbody>
											<tr>
												<td>Last Played</td>
												<td>09 Jan '14</td>
											</tr>

											<tr>
												<td>Unique Opponents</td>
												<td>9</td>
											</tr>
											<tr>
												<td>Unique Venues</td>
												<td>4</td>
											</tr>
											<tr>
												<td>Friendly Matches</td>
												<td>20</td>
											</tr>
											<tr>
												<td>League Matches</td>
												<td>2</td>
											</tr>
											<tr>
												<td>Knockout Matches</td>
												<td>1</td>
											</tr>


										</tbody>


									</table>