<table class="table box-stats-table table-bordered">
										<thead>
											<tr>
												<td colspan="2">
													<p class="text-center">Performance</p>
												</td>
											</tr>

										</thead>

										<tbody>
											<tr>
												<td>Rank</td>
												<td><?php echo is_numeric($this->player['siteRank']) ? $this->player['siteRank'] : 'Unrated *'; ?></td>
											</tr>

											<tr>
												<td>Points</td>
												<td><?php echo is_numeric($this->player['siteRank']) ? number_format($this->player['rankingPoints'], 0) : 'N/A'; ?></td>
											</tr>
											<tr>
												<td>Percentile</td>
												<td><?php echo is_numeric($this->player['siteRank']) ? 'Top ' . $this->player['percentile'] . '%' : 'N/A'; ?></td>
											</tr>
											<tr>
												<td>W/L/D</td>

												<td><?php echo $this->player['matchesWon'] ?>/<?php echo $this->player['matchesDrawn'] ?>/<?php echo $this->player['matchesLost'] ?></td>
											</tr>



										</tbody>


									</table>