<table class="table box-stats-table table-bordered">
										<thead>
											<tr>
												<td colspan="2">
													<p class="text-center">Performance</p>
												</td>
											</tr>

										</thead>

										<tbody>
											<tr>
												<td>Rank</td>
												<td><?php echo $this->player['siteRank']; ?></td>
											</tr>

											<tr>
												<td>Points</td>
												<td>Unrated</td>
											</tr>
											<tr>
												<td>Percentile</td>
												<td>Unrated</td>
											</tr>
											<tr>
												<td>W/L/D</td>
												<td>15/4/1</td>
											</tr>



										</tbody>


									</table>