<table class="table box-stats-table table-bordered">
					<thead>
						<tr>
							<td colspan="2">
								<p class="text-center">Player Profile</p>
							</td>
						</tr>

					</thead>

					<tbody>
<tr>
												<td>Name</td>
												<td><?php echo $this->player['name']; ?></td>
											</tr>

											<tr>
												<td>Gender</td>
												<td><?php echo $this->player['sex']; ?></td>
											</tr>
											<tr>
												<td>Joined</td>
												<td><?php echo $this->player['joinDate']; ?></td>
											</tr>
											<tr>
												<td>User Rating</td>
												<td><?php echo $this->player['userRating']; ?></td>
											</tr>
											<tr>
												<td>LTA Number</td>
												<td><?php echo $this->player['ltaNumber']; ?></td>
											</tr>
											<tr>
												<td>LTA Rating</td>
												<td><?php echo $this->player['ltaRating']; ?></td>
											</tr>


					</tbody>


				</table>