<div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                                <div class="filters">
                                      <ul class="nav-tabs nav">
                                      <li class="active"><a href="<?php echo $this->url('players'); ?>">Search Players</a></li>
                                      <li ><a href="<?php echo $this->url('players/most-played'); ?>">Most Played</a></li>
                                      <li ><a href="<?php echo $this->url('players/most-wins'); ?>">Most Wins</a></li>
                                      <li ><a href="<?php echo $this->url('players/recently-played'); ?>">Recently Played</a></li>
                                      <li ><a href="<?php echo $this->url('players/currently-played'); ?>">Currently Played</a></li>
                                      <li ><a href="<?php echo $this->url('players/top-ranked'); ?>">Top Ranked</a></li>
                                      <li ><a href="<?php echo $this->url('players/recent-joiners'); ?>">Recent Joiners</a></li>
                                      </ul>
                                </div>
                                
                                <p class="description">This service is designed for you to be able to find a player in an area near you who is free and willing to play.
The more criteria you use, the narrower the search results will be. If you obtain no results, try reducing the number of criteria that you use.</p>
                            </div>

</div>