
        <div class="filters">
          <ul class="nav-tabs nav">
          
          <?php echo $this->subMenuOption('players/search', 'Search', 'active'); ?>
          <?php echo $this->subMenuOption('players/most-played', 'Most Played', 'active'); ?>
          <?php echo $this->subMenuOption('players/most-wins', 'Most Wins', 'active'); ?>
          <?php echo $this->subMenuOption('players/recently-played', 'Recently Played', 'active'); ?>
          <?php echo $this->subMenuOption('players/currently-online', 'Currently Online', 'active'); ?>
          <?php echo $this->subMenuOption('players/top-ranked', 'Top Ranked', 'active'); ?>
          <?php echo $this->subMenuOption('players/recent-joiners', 'Recent Joiners', 'active'); ?>

          </ul>
       </div>
