<table class="table box-stats-table table-bordered">
										<thead>
											<tr>
												<td colspan="2">
													<p class="text-center">Tennis Preferences</p>
												</td>
											</tr>

										</thead>

										<tbody>
											<tr>
												<td>Play Radius</td>
												<td><?php echo $this->player['milesRadius']; ?></td>
											</tr>

											<tr>
												<td>Opponents</td>
												<td><?php echo $this->player['opponentSex']; ?></td>
											</tr>
											<tr>
												<td>Format</td>
												<td><?php echo $this->player['format']; ?></td>
											</tr>
											<tr>
												<td>Times</td>
												<td><?php echo $this->player['availability']; ?></td>
											</tr>
											<tr>
												<td>Home Venue</td>
												<td><?php echo $this->clubLink($this->player['homeClubId'], $this->player['homeClubName']); ?></td>
											</tr>



										</tbody>


									</table>
