                                <div class="filters">
                                      <ul class="nav-tabs nav">
                                      <li class="active"><a href="<?php echo $this->url('courts/search'); ?>">Find Court</a></li>
                                      <li ><a href="<?php echo $this->url('courts/popular'); ?>">Most Popular Courts</a></li>
                                      <li ><a href="<?php echo $this->url('courts/favourites'); ?>">My Favourite Courts</a></li>
                                

                                       </ul>
                                </div>