                                <div class="filters">
                                      <ul class="nav-tabs nav">
                                      
                                      <?php echo $this->subMenuOption('courts/search', 'Find Court', 'active'); ?>
                                      <?php echo $this->subMenuOption('courts/popular', 'Most Popular Courts', 'active'); ?>
                                      <?php echo $this->subMenuOption('courts/favourites', 'My Favourite Courts', 'active'); ?>
                    
                                       </ul>
                                </div>