<div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>COMPETITIONS</h1>
                      </div>
                      

                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                                <div class="filters">
                                       <ul class="nav-tabs nav">
                                      
                                      
                                     <li  class="active"  ><a href="competition-ko-current.html">Current Draws</a></li>
                                      <li ><a href="competition-ko-sign.html">Previous Draws</a></li>
                                      <li ><a href="competition-ko-sign.html">KO Info &amp; Sign-up</a></li>
                                        
                                       

                                       </ul>
                                </div>
                                
                                <p class="description">The London Tennis Knockout is now our only competition, but it has been made a triannual event, with our next tournament starting 16 February 2015 offering Ladies' and Men's events to players from 16 years.

Trophies and prize money of up to £200 for the winner of the main draw, plus new consolation draws giving a second chance to win prize money and the chance to play in a final at the National Tennis Centre.

Sign up <a href="#ko-signup">here</a> </p>
                            </div>

                        </div>
                        

                        
                        
                        
                        <div class="row">

          <div class="filters table-filter">
                                      <ul class="nav-tabs nav">
                                      <li class="active" ><a href="#ko=men">Men</a></li>
                                      <li ><a href="#ko-ladies">Ladies</a></li>
                                                            

                                       </ul>
                                </div>
          
    
                          <div class="col-lg-10 col-lg-offset-1 ">
                                  
                                  
                                  
                                   <div class="division-name">
                                  <p>The 2014 London Tennis Summer Knockout Finals</p>
                                  <p class="table-note">Semi Finals to be played by 22 December</p>
                                  
                                  
                              </div>
                                <div class="ko-table table-responsive">
                                  <table class="table table-bordered ko-table">
                                   
                                    
                                    <tbody>
                                       
                                    
                                       
                                        <tr>
                                            <td class="league-title">Round 1</td>
                                            <td class="league-title">Round 2</td>
                                            
                                            
                                            
                                            <td class="league-title">Quarter Finals</td>
                                            <td class="league-title">Semi Finals</td>
                                            <td class="league-title">Final</td>
                                           
                                      
                                           
                                           
                                            
                                        </tr>
                                        
                                        <tr>
                                           <td class="ko-data">
                                           <a class="winner" href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player2</a>(5)
                                           <br>
                                           <p>6-3 5-0</p>
                                           </td>
                                           
                                           <td rowspan="2" class="ko-data data-center round-2">
                                               <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a class="winner"  href="#player">player4</a>(15)
                                           <br>
                                           <p>6-3 5-0</p>
                                               
                                           </td>
                                           
                                           <td rowspan="4" class="ko-data data-center">
                                               <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a class="winner"  href="#player">player4</a>(15)
                                           <br>
                                           <p>6-3 5-0</p>
                                               
                                           </td>
                                           
                                           <td rowspan="8" class="ko-data data-center semi-finals">
                                               <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a class="winner"  href="#player">player4</a>(15)
                                           <br>
                                           <p>6-3 5-0</p>
                                               
                                           </td>
                                           
                                           <td rowspan="16" class="ko-data data-center finals">
                                               <a class="winner"  href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-3 5-0</p>
                                               
                                           </td>
                                           
                                            
                                        </tr>
                                        
                                         <tr>
                                           <td class="ko-data">
                                           <a href="#player">player3</a>(20)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-0 6-1</p>
                                           </td>
                                           
                                            
                                        </tr>
                                        
                                        <tr>
                                           <td class="ko-data">
                                           <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player2</a>(5)
                                           <br>
                                           <p>6-3 5-0</p>
                                           </td>
                                           
                                           <td rowspan="2" class="ko-data data-center">
                                               <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-3 5-0</p>
                                               
                                           </td>
                                           
                                            
                                        </tr>
                                        
                                         <tr>
                                           <td class="ko-data">
                                           <a href="#player">player3</a>(20)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-0 6-1</p>
                                           </td>
                                           
                                            
                                        </tr>
                                        
                                       <!-- Four games    -->
                                        
                                        <tr>
                                           <td class="ko-data">
                                           <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player2</a>(5)
                                           <br>
                                           <p>6-3 5-0</p>
                                           </td>
                                           
                                           <td rowspan="2" class="ko-data data-center">
                                               <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-3 5-0</p>
                                               
                                           </td>
                                           
                                           <td rowspan="4" class="ko-data data-center">
                                               <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-3 5-0</p>
                                               
                                           </td>
                                           
                                            
                                        </tr>
                                        
                                         <tr>
                                           <td class="ko-data">
                                           <a href="#player">player3</a>(20)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-0 6-1</p>
                                           </td>
                                           
                                            
                                        </tr>
                                        
                                      <tr>
                                           <td class="ko-data">
                                           <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player2</a>(5)
                                           <br>
                                           <p>6-3 5-0</p>
                                           </td>
                                           
                                           <td rowspan="2" class="ko-data data-center">
                                               <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-3 5-0</p>
                                               
                                           </td>
                                           
                                            
                                        </tr>
                                        
                                         <tr>
                                           <td class="ko-data">
                                           <a href="#player">player3</a>(20)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-0 6-1</p>
                                           </td>
                                           
                                            
                                        </tr>
                                        
                                        <!-- Four games    -->
                                        
                                        <tr>
                                           <td class="ko-data">
                                           <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player2</a>(5)
                                           <br>
                                           <p>6-3 5-0</p>
                                           </td>
                                           
                                           <td rowspan="2" class="ko-data data-center">
                                               <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-3 5-0</p>
                                               
                                           </td>
                                           
                                           <td rowspan="4" class="ko-data data-center">
                                               <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-3 5-0</p>
                                               
                                           </td>
                                           
                                           <td rowspan="8" class="ko-data data-center semi-finals">
                                            <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-3 5-0</p>
                                               
                                           </td>
                                           
                                            
                                        </tr>
                                        
                                         <tr>
                                           <td class="ko-data">
                                           <a href="#player">player3</a>(20)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-0 6-1</p>
                                           </td>
                                           
                                            
                                        </tr>
                                        
                                      <tr>
                                           <td class="ko-data">
                                           <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player2</a>(5)
                                           <br>
                                           <p>6-3 5-0</p>
                                           </td>
                                           
                                           <td rowspan="2" class="ko-data data-center">
                                               <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-3 5-0</p>
                                               
                                           </td>
                                           
                                            
                                        </tr>
                                        
                                         <tr>
                                           <td class="ko-data">
                                           <a href="#player">player3</a>(20)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-0 6-1</p>
                                           </td>
                                           
                                            
                                        </tr>
                                        
                                      
                                        <!-- Four games    -->
                                        
                                        <tr>
                                           <td class="ko-data">
                                           <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player2</a>(5)
                                           <br>
                                           <p>6-3 5-0</p>
                                           </td>
                                           
                                           <td rowspan="2" class="ko-data data-center">
                                               <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-3 5-0</p>
                                               
                                           </td>
                                           
                                           <td rowspan="4" class="ko-data data-center">
                                               <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-3 5-0</p>
                                               
                                           </td>
                                           
                                            
                                        </tr>
                                        
                                         <tr>
                                           <td class="ko-data">
                                           <a href="#player">player3</a>(20)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-0 6-1</p>
                                           </td>
                                           
                                            
                                        </tr>
                                        
                                      <tr>
                                           <td class="ko-data">
                                           <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player2</a>(5)
                                           <br>
                                           <p>6-3 5-0</p>
                                           </td>
                                           
                                           <td rowspan="2" class="ko-data data-center">
                                               <a href="#player">player1</a>(2)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-3 5-0</p>
                                               
                                           </td>
                                           
                                            
                                        </tr>
                                        
                                         <tr>
                                           <td class="ko-data">
                                           <a href="#player">player3</a>(20)
                                           <p>vs</p>
                                           <a href="#player">player4</a>(15)
                                           <br>
                                           <p>6-0 6-1</p>
                                           </td>
                                           
                                            
                                        </tr>
                                        
                                        
                                      
                                        
                                       
                                        
                                        
                                    </tbody>
                               
                                 
                                 
                                 
                                </table>
  
                                </div>
                                  
                          
                          
                          
                            </div>
                        </div>
                        
                        
                                             
                        
                        
                        
                        
                        
                        
                        
                        
                        
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>