<div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>COMPETITIONS</h1>
                      </div>
                      
                      
                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                                <?php echo $this->partial('application/competitions/partials/subnav.phtml'); ?>
                                
                                <p class="description">Sign up for the Winter 2015 Knockout Tournament
                                </p>
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-lg-10 col-lg-offset-1">
                               <form class="form-horizontal" role="form" method="post">
  <div class="form-group">
    <label for="start-date" class="col-sm-2 control-label">Start Date:</label>
    <div class="col-sm-8 start-date">
      <p>The Winter 2015 tournament starts on January 11th 2015.</p>
      <p>If you encounter any problems with the process, please use the help tab and we will answer any questions you may have.
  <br><br>
Once payment is complete you will be redirected to the My Payments link above which contains details of any payments you make London Tennis order.</p>    
      
    </div>
  </div>

<div class="submit col-lg-2 ">
   <button type="submit" name="findplayerbutton" class="btn btn-pay ">Continue to PayPal</button>  
    
</div>

</form>
                               
                                
                                
                            </div>
                            
                            
                        </div>
                        
                        
                                
                                <div class="row">
                                    <div class="col-lg-10 col-lg-offset-1 court-comments">
                                          <p class="venue-title">rules and information</p>
                                       
                                          <div class="info-row">
                                              <div class="info-head">
                                                    <p>Players</p>
                                              </div>
                                              <div class="info-explain">
                                                The London Tennis Knock-out Tournaments are for men and women sixteen years and over on the 1st of January 2009.
<br><br>
All matches must be played within a 25 mile radius of Charing Cross (use form below to check distance).


                                                  
                                              </div>
                                              
                                              
                                              
                                              
                                          </div>
                                          
                                          
                                          <form class="form-horizontal" role="form" method="post">
                                              <div class="form-group">
    <label for="player-name" class="col-sm-1 control-label">Postcode</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="player-name" placeholder="eg. Wimbledon Park">
    </div>
    <div class="col-sm-3">
        <button type="submit" name="findcourt" class="btn btn-green">Check Distance</button>  
        
    </div>
    
  </div>
                                         
                                         
                                          
                                        </form>
                                        
                                        
                                        <div class="info-row">
                                              
                                              <div class="info-explain">
                                              LTA rated players are welcome, but an LTA rating is not required to enter the tournament - for information about standards please take a look at the ratings information page - you will need to choose a rating when setting up your membership profile - membership is free and players must be members to enter the event. Players are asked to use best judgement when rating themselves and read the ratings section carefully when choosing a rating.


                                                  
                                              </div>
                                              
                                              
                                              
                                              
                                          </div>
                                          
                                         
                                         
                                          
                                         
                                          
                                          
                                          
                                          
                                          
                                          
                                           
                                          
                                          <div class="info-row">
                                              <div class="info-head">
                                                    <p>Knock-out play format</p>
                                              </div>
                                            <div class="info-explain">
                                                  Leagues run in four seasons throughout the year in the London regions - West, SW, NW, North, East, SE and the homecounties of Surrey &amp; Middlesex.
                                                  
                                              </div>
                                              
                                              
                                          </div>
                                          
                                          
                                          <div class="info-row">
                                              <div class="info-head">
                                                    <p>League play format </p>
                                              </div>
                                            <div class="info-explain">
                                              Players are placed into the draw and seeding will occur where LTA or ITN or London Tennis site ranking will be accounted for.
<br><br>
Players may need to travel for some of their matches, although there will be a nominated home and away player in each round of the draw.
<br><br>
Each match will have a published deadline by which time one of the following must have happened:.
                                             
                                             <ul class="terms">
                                                 <li>The match has been played and the result entered on the site.</li>
                                                 <li>A walkover has been claimed by one of the players. Please see the section on walkovers below for details of when a walkover may be claimed.</li>
                                                 <li>A message has been sent to the London Tennis admins giving details of when the match can be played, it is however unlikely that extensions will be given.</li>
 </ul>
                                            
                                                                                             <br>
                                                 In situations where none of the above has occured, the match will be declared void.
                                                 
                                             
                                              </div>
                                              
                                              
                                          </div>
                                          
                                          
                                          <div class="info-row">
                                              <div class="info-head">
                                                    <p>Trophies and Prizes</p>
                                              </div>
                                            <div class="info-explain">
                                               The finalists of the events will receive vouchers to use at <a href="http://www.sweatband.com">www.sweatband.com</a> - £50 to each winner and £25 to each runner-up. There will also be winner and runner-up trophies and London Tennis Tee Shirts for all finalists.
                                                  
                                              </div>
                                              
                                              
                                          </div>
                                          
                                          
                                          <div class="info-row">
                                              <div class="info-head">
                                                    <p>Arranging Matches</p>
                                              </div>
                                            <div class="info-explain">
                                               We strongly urge players to try to complete all of their matches in fairness to all players.
<br><br>
Both players are responsible for contacting each other using email and all telephone numbers provided. Phone numbers may be displayed to knock-out opponents only.
<br><br>
Matches should be scheduled in the first of the three weeks given to play. Contact with your opponent should be made via the telephone as well as email and online diaries can be used to assist in scheduling matches.
<br><br>
If you have attempted to contact your opponent at least twice, at all listed numbers and received no reply by the end of the first week of play then you may claim a walkover for that match.
                                              </div>
                                              
                                              
                                          </div>
                                          
                                          
                                          
                                          
                                          
                                          
                                          
                        
                                          
                                          <div class="info-row">
                                              <div class="info-head">
                                                    <p>Balls</p>
                                              </div>
                                            <div class="info-explain">
Both players should bring a new can of four tennis balls to the match. You can then toss a coin to open a can. The match winner gets the unopened can and the loser gets the balls used in the match.
                                              </div>
                                              
                                              
                                          </div>
                                          
                                          <div class="info-row">
                                              <div class="info-head">
                                                    <p>Court Fees</p>
                                              </div>
                                            <div class="info-explain">
Costs must split equally between the two players. Club guest fees should be played by the away player up to £6, the rest made up by home player.
                                              </div>
                                              
                                              
                                          </div>
                                          
                                          
                                          <div class="info-row">
                                              <div class="info-head">
                                                    <p>Warm Up</p>
                                              </div>
                                            <div class="info-explain">
Players should spend a maximum of 10 minutes warming up for the match.
                                              </div>
                                              
                                              
                                          </div>
                                          
                                          
                                          <div class="info-row">
                                              <div class="info-head">
                                                    <p>Match Format</p>
                                              </div>
                                            <div class="info-explain">
Best of three sets with a tie-break at 6-6 in all sets. At 1 set all, if both players agree, the match can be decided by a tie-break to 10 points, by a 2 point margin.
                                              </div>
                                              
                                              
                                          </div>
                                          
                                          
                                          <div class="info-row">
                                              <div class="info-head">
                                                    <p>Line calls</p>
                                              </div>
                                            <div class="info-explain">
Please give the benefit of your doubts to your opponents. Only call the lines on your side of the net.
                                              </div>
                                              
                                              
                                          </div>
                                          
                                          
                                                   <div class="info-row">
                                              <div class="info-head">
                                                    <p>Unfinished Matches</p>
                                              </div>
                                            <div class="info-explain">
Unfinished matches can be completed on another date and can be resumed where play has finished to the nearest game, though the match must be completed by the required deadline.
                                              </div>
                                              
                                              
                                          </div>
                                          
                                          
                                          <div class="info-row">
                                              <div class="info-head">
                                                    <p>Results</p>
                                              </div>
                                            <div class="info-explain">Results should be entered by the winning player within a day of the match being completed. For matches played on the last day permitted results should be entered immediately or will be inadmissible.

                                              </div>
                                              
                                              
                                          </div>
                                          
                                          
                                          <div class="info-row">
                                              <div class="info-head">
                                                    <p>Conduct</p>
                                              </div>
                                            <div class="info-explain">All matches prior to finals are played without officials, so players must conduct themselves in a sportsmanlike manner both on and off the court. This includes:
                                              
                                              <ul class="terms">
                                                 <li>Responding promptly to phone calls/emails from opponents.</li>
                                                 <li>Playing matches on time and reporting scores accurately within the given time period</li>
                                                 <li>Notifying opponents in advance when a match cannot be played for any reason</li>
                                                 <li>Arriving on time for matches</li>
                                                 <li>Uderstanding and abiding by the rules</li>
                                                 <li>Refraining from swearing or aggressive shouting</li>
 </ul>
                                              <br>
                                              We ask that all league players should report any incidents of unsportsmanlike conduct to us, so that we can monitor such players and remove persistent offenders from the leagues altogether.
                                              <br><br>
                                              Players who use physical abuse or threaten to use physical abuse or enter false results will be immediately removed from the leagues.

                                              </div>
                                              
                                              
                                          </div>
                                          
                                          
                                          
      
                                          
                                          
                                          <div class="info-row">
                                              <div class="info-head">
                                                    <p>Walkovers</p>
                                              </div>
                                            <div class="info-explain">To signify a walkover, please enter the result as a single set match scoring 1-0 to the winner.
                                             <br><br>
                                              Walkovers can be claimed when your opponent:
                                              
                                              <ul class="terms">
                                                 <li>Doesn't respond to their opponent's phone calls at all numbers after two attempts over at least two days or by noon of Thursday preceding the scheduled week of play; or is unavailable for any reason to play the match during the scheduled week of play.</li>
                                                 <li>Doesn't show up for the match.</li>
                                                 <li>Shows up more than 20 minutes late.</li>
                                                 <li>Doesn't give four hours notice for match cancellations.</li>
                                                 <li>Cancels a rescheduled match at any time.</li>
                                                 <li>Doesn't complete the match.</li>
                                                 <li>Offers you a walkover due to unavailability.</li>
 </ul>
                                              
                                             

                                              </div>
                                              
                                              
                                          </div>
                                          
                                          <div class="info-row">
                                              <div class="info-head">
                                                    <p>Refunds</p>
                                              </div>
                                            <div class="info-explain">If you sign up to play and for some reason do not play please do not request a refund.

                                              </div>
                                              
                                              
                                          </div>
                                          
                                          
                                          
                                          
                                       
                                       
                                        
                                        
                                    </div>              
                                    
                                    
                                </div>
                                
                                
                                
                        
                        
                                            
                        
                        
    
                        
                       <!-- end of paper  -->
                        
                     </div>  
                <!--   end of content   -->
                   </div>
                   
               </div>
               
           </div>
           
</div>