<div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>FORUM</h1>
                      </div>
                      
                      
                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                                <?php echo $this->partial('application/forums/partials/subnav.phtml');?>
                                
                                <p class="description"></p>
                                
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-lg-10 col-lg-offset-1">
                               <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th class="image-head"></th>
                                            <th>Forum Name</th>
                                            <th>Last Post</th>
                                            
                                            
                                        </tr>
                                        
                                    </thead>
                                    
                                    <tbody>
                                        <tr class="forum-row">
                                            <td class="image-td"><img class="forum-ball" src="img/ball2.png" alt=""></td>
                                            <td><a href="forum-general-chat.html">General</a> <br>General Discussion.</td>
                                            <td class="forum-date">11 Jan '15 20:23</td>
                                            
                                        </tr>
                                        
                                        
                                        <tr class="forum-row">
                                            <td class="image-td"><img src="img/ball2.png" alt=""></td>
                                            <td><a href="forum-general-chat.html">Meet Opponenets</a> <br>Use this forum to meet your perfect tennis partners!</td>
                                            <td class="forum-date">11 Jan '15 20:23</td>
                                            
                                        </tr>
                                        
                                        <tr class="forum-row">
                                            <td class="image-td"><img src="img/ball2.png" alt=""></td>
                                            <td><a href="forum-general-chat.html">Site Feedback, Ideas and Comments</a> <br>Use this forum to recommend features for the site or to make comments on existing features.</td>
                                            <td class="forum-date">11 Jan '15 20:23</td>
                                            
                                        </tr>
                                        
                                        <tr class="forum-row">
                                            <td class="image-td"><img src="img/ball2.png" alt=""></td>
                                            <td><a href="forum-general-chat.html">Equipment For Sale</a> <br>If your post relates to the sale of some tennis equipment, please put it here.<br>
Please note that London Tennis cannot be responsible for any deals struck on this forum!</td>
                                            <td class="forum-date">11 Jan '15 20:23</td>
                                            
                                        </tr>
                                        
                                        
                                        
                                        
                                        
                                    </tbody>
                               
                                 
                                 
                                 
                                </table>
                            </div>
                                
                                
                                
                                
                                
                            </div>
                            
                            
                        </div>
                        
                        
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>