<div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>FORUM</h1>
                      </div>
                      
                      
                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                                <?php echo $this->partial('application/forums/partials/subnav.phtml');?>
                                
                                <p class="description"></p>
                                
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-lg-10 col-lg-offset-1">
                               <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th class="image-head"></th>
                                            <th>Forum Name</th>
                                            <th>Last Post</th>
                                            
                                            
                                        </tr>
                                        
                                    </thead>
                                    
                                    <tbody>
                                    
                                        <?php foreach ($this->forums as $forum): ?>
                                        <tr class="forum-row">
                                            <td class="image-td"><img class="forum-ball" src="img/ball2.png" alt=""></td>
                                            <td>
                                                <a href="<?php echo $this->url('forums/view-forum', ['forumid' => $forum['forumid']]); ?>">
                                                    <?php echo $forum['forumname']; ?>
                                                </a>
                                            <br>
                                            <?php echo $forum['forumdesc']; ?></td>
                                            <td class="forum-date"><?php echo $forum['forumlastpostdate']; ?></td>
                                            
                                        </tr>
                                        <?php endforeach; ?>
                                        
                                        
                                    </tbody>
                               
                                 
                                 
                                 
                                </table>
                            </div>
                                
                                
                                
                                
                                
                            </div>
                            
                            
                        </div>
                        
                        
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>