<div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>FORUM</h1>
                      </div>
                      
                      
                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                                <?php echo $this->partial('application/forums/partials/subnav.phtml');?>
                                
                                <p class="chat-options">
                                    
                                    <a href="forum-new-post-reply.html"> <span class="glyphicon glyphicon-plus"></span> New Post</a>
                                    <a href="forum-new-post-reply.html"> <span class="glyphicon glyphicon-list"></span> Thread List</a>
                                    <a href="forum-new-post-reply.html"> <span class="glyphicon glyphicon-sort-by-attributes"></span> Last Post</a>
                                    <a href="forum-new-post-reply.html"> <span class="glyphicon glyphicon-star"></span> Subscribe</a>
                                </p>
                                
                                <p class="subscribed"><span class="glyphicon glyphicon-ok"></span>Thank you. You will now receive email notifications for this thread.</p>
                                
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-lg-10 col-lg-offset-1">
                               <div class="table-responsive">
                                <table class="table table-striped table-bordered forum-table">
                                    <thead>
                                    
                                        
                                    </thead>
                                    
                                    <tbody>
                                        <tr class="forum-row">
                                            <td class="image-td"><img class="forum-ball" src="img/ball2.png" alt=""></td>
                                            <td><a href="forum-general-chat.html">General</a> <br><span class="infovalue">Fournis - tennis australia stole my idea!</span></td>
                                            
                                            
                                        </tr>
                                        
                                        
 
                                        
                                    </tbody>
                                    
                                      <thead>
                                        <tr>
                                            <th >Poster</th>
                                            <th>Message</th>
                                           
                                            
                                            
                                        </tr>
                                        
                                    </thead>
                                    
                                    <tbody>
                                       
                                      <!-- thread post  -->
                                       
                                        <tr class="post-light">
                                            <td class="poster"><a href="#poster">casper323</a> </td>
                                            <td class="forum-post">
                                                <span class="posteddate forum-date">08 jan '15 02:14 : 0 recs</span>
                                               <p>
                                                                                                   Are there any clubs in the Worcester Park area that have clay courts? 
<br><br>
Not really interested in Sutton Tennis Academy as that is rather unpleasant clay.
                                                   
                                                   
                                               </p>

                                                
                                            </td>
                                            
                                        </tr>
                                        
                                        <tr class="row-shadow">
                                           <td class="edge"><div ></div></td>
                                           <td class="reply">
                                            <div class="reply-section clearfix">
                                                   <a href="forum-new-post-reply.html"><span class="glyphicon glyphicon-share-alt"></span> Reply</a>
                                             <a href="forum-new-post-reply.html">Reply &amp; Quote</a>
                                                
                                            </div>
                                           
                                          
                                           
                                           
                                           </td>
                                           
                                        </tr>
                                        
                                        <tr>
                                            <td colspan="2" class="rowspacer">
                                              
                                            </td>
                                            
                                        </tr>
                                        
                                      <!--  end of new post  -->
                                      
                                       <!-- thread post  -->
                                       
                                        <tr class="post-light">
                                            <td class="poster"><a href="#poster">casper323</a> </td>
                                            <td class="forum-post">
                                                <span class="posteddate forum-date">08 jan '15 02:14 : 0 recs</span>
                                               <p>
                                                                                                   Are there any clubs in the Worcester Park area that have clay courts? 
<br><br>
Not really interested in Sutton Tennis Academy as that is rather unpleasant clay.
                                                   
                                                   
                                               </p>

                                                
                                            </td>
                                            
                                        </tr>
                                        
                                        <tr class="row-shadow">
                                           <td class="edge"><div ></div></td>
                                           <td class="reply">
                                            <div class="reply-section clearfix">
                                                   <a href="forum-new-post-reply.html"><span class="glyphicon glyphicon-share-alt"></span> Reply</a>
                                             <a href="forum-new-post-reply.html">Reply &amp; Quote</a>
                                                
                                            </div>
                                           
                                          
                                           
                                           
                                           </td>
                                           
                                        </tr>
                                        
                                        <tr>
                                            <td colspan="2" class="rowspacer">
                                              
                                            </td>
                                            
                                        </tr>
                                        
                                      <!--  end of new post  -->
                                      
                                       <!-- thread post  -->
                                       
                                        <tr class="post-light">
                                            <td class="poster"><a href="#poster">casper323</a> </td>
                                            <td class="forum-post">
                                                <span class="posteddate forum-date">08 jan '15 02:14 : 0 recs</span>
                                               <p>
                                                                                                   Are there any clubs in the Worcester Park area that have clay courts? 
<br><br>
Not really interested in Sutton Tennis Academy as that is rather unpleasant clay.
                                                   
                                                   
                                               </p>

                                                
                                            </td>
                                            
                                        </tr>
                                        
                                        <tr class="row-shadow">
                                           <td class="edge"><div ></div></td>
                                           <td class="reply">
                                            <div class="reply-section clearfix">
                                                   <a href="forum-new-post-reply.html"><span class="glyphicon glyphicon-share-alt"></span> Reply</a>
                                             <a href="forum-new-post-reply.html">Reply &amp; Quote</a>
                                                
                                            </div>
                                           
                                          
                                           
                                           
                                           </td>
                                           
                                        </tr>
                                        
                                        <tr>
                                            <td colspan="2" class="rowspacer">
                                              
                                            </td>
                                            
                                        </tr>
                                        
                                      <!--  end of new post  -->
                                      
                                       <!-- thread post  -->
                                       
                                        <tr class="post-light">
                                            <td class="poster"><a href="#poster">casper323</a> </td>
                                            <td class="forum-post">
                                                <span class="posteddate forum-date">08 jan '15 02:14 : 0 recs</span>
                                               <p>
                                                                                                   Are there any clubs in the Worcester Park area that have clay courts? 
<br><br>
Not really interested in Sutton Tennis Academy as that is rather unpleasant clay.
                                                   
                                                   
                                               </p>

                                                
                                            </td>
                                            
                                        </tr>
                                        
                                        <tr class="row-shadow">
                                           <td class="edge"><div ></div></td>
                                           <td class="reply">
                                            <div class="reply-section clearfix">
                                                   <a href="forum-new-post-reply.html"><span class="glyphicon glyphicon-share-alt"></span> Reply</a>
                                             <a href="forum-new-post-reply.html">Reply &amp; Quote</a>
                                                
                                            </div>
                                           
                                          
                                           
                                           
                                           </td>
                                           
                                        </tr>
                                        
                                        <tr>
                                            <td colspan="2" class="rowspacer">
                                              
                                            </td>
                                            
                                        </tr>
                                        
                                      <!--  end of new post  -->
                                      
                                       <!-- thread post  -->
                                       
                                        <tr class="post-light">
                                            <td class="poster"><a href="#poster">casper323</a> </td>
                                            <td class="forum-post">
                                                <span class="posteddate forum-date">08 jan '15 02:14 : 0 recs</span>
                                               <p>
                                                                                                   Are there any clubs in the Worcester Park area that have clay courts? 
<br><br>
Not really interested in Sutton Tennis Academy as that is rather unpleasant clay.
                                                   
                                                   
                                               </p>

                                                
                                            </td>
                                            
                                        </tr>
                                        
                                        <tr class="row-shadow">
                                           <td class="edge"><div ></div></td>
                                           <td class="reply">
                                            <div class="reply-section clearfix">
                                                   <a href="forum-new-post-reply.html"><span class="glyphicon glyphicon-share-alt"></span> Reply</a>
                                             <a href="forum-new-post-reply.html">Reply &amp; Quote</a>
                                                
                                            </div>
                                           
                                          
                                           
                                           
                                           </td>
                                           
                                        </tr>
                                        
                                        <tr>
                                            <td colspan="2" class="rowspacer">
                                              
                                            </td>
                                            
                                        </tr>
                                        
                                      <!--  end of new post  -->
                                      
                                       
                                       
                                       
                 
                                        
                                        
                                        
                                        
                                        
                                    </tbody>
                               
                                 
                                 
                                 
                                </table>
                            </div>
                                
                                
                                <nav class="page-pagination">
  <ul class="pagination">
    <li>
      <a href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li class="active"><a  href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li>
      <a href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
  <p>Showing posts 1 to 20 of 25</p>
</nav>
                                
                                
                            </div>
                            
                            
                        </div>
                        
                        
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>