<div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>FORUM</h1>
                      </div>
                      
                      
                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                                
                                    <?php echo $this->partial('application/forums/partials/subnav.phtml');?>
                                     
                                
                                <p class="add-thread">
                                    
                                    <a href="<?php echo $this->url('forums/view-forum/new-thread', ['forumid' => $this->routeParams()['forumid']]); ?>"> <span class="glyphicon glyphicon-plus"></span> New Thread</a>
                                </p>
                                
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-lg-10 col-lg-offset-1">
                               <div class="table-responsive">
                                <table class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Thread</th>
                                            <th>Posts</th>
                                            <th>Last Post</th>
                                            <th>Created By</th>
                                            <th>Last Poster</th>
                                            
                                            
                                        </tr>
                                        
                                    </thead>
                                    
                                    <tbody>
                                      
                                      <?php foreach ($this->threads as $thread): ?>
                                      
                                      <tr class="forum-list">
                                          <td>
                                              <a href="<?php echo $this->url('forums/view-forum/view-thread', ['forumid' => $this->routeParams()['forumid'], 'threadid' => $thread['id']]); ?>">
                                                <?php echo $thread['subject']; ?>
                                              </a>
                                          </td>
                                          <td><?php echo $thread['postCount']; ?></td>
                                          <td><a class="forum-date" href="#last-post"><?php echo $thread['lastPostTime']; ?></a></td>
                                          <td><?php echo $this->playerLink($thread['creatorId'], $thread['creatorName']); ?></td>
                                          <td><?php echo $this->playerLink($thread['lastPosterId'], $thread['lastPosterName']); ?></td>
                                      </tr>
                                      
                                        <?php endforeach; ?>
                                          
                                        
                                    </tbody>
                               
                                 
                                 
                                 
                                </table>
                            </div>
                                
                                <nav class="page-pagination">
  <ul class="pagination">
    <li>
      <a href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li class="active"><a  href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li>
      <a href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
  <p>Showing posts 1 to 30 of 2148</p>
</nav>
                                
                                
                                
                            </div>
                            
                            
                        </div>
                        
                        
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>