                                <div class="filters">
<ul class="nav-tabs nav">
                                      <li ><a href="<?php echo $this->url('forums'); ?>">Forum List</a></li>
                                      <li class="active" ><a href="<?php echo $this->url('forums/view-forum', ['forumid' => 1]); ?>">General Chat</a></li>
                                      <li ><a href="<?php echo $this->url('forums/view-forum', ['forumid' => 2]); ?>">Meet Opponenets</a></li>
                                      <li ><a href="<?php echo $this->url('forums/view-forum', ['forumid' => 3]); ?>">Site Comments &amp; Feedback</a></li>
                                      <li ><a href="<?php echo $this->url('forums/view-forum', ['forumid' => 4]); ?>">Equipment for Sale</a></li>

                                       </ul>
                                       </div>