                                <div class="filters">
<ul class="nav-tabs nav">

<?php echo $this->subMenuOption('forums', 'Forum List', 'active'); ?>

<?php foreach ($this->forums as $forum): ?>
                                        <?php echo $this->subMenuOption('forums/view-forum', $forum['forumname'], 'active', ['forumid' => $forum['forumid']]); ?>

                                        <?php endforeach; ?>

                                       </ul>
                                       </div>