<div class="filters">
                                       <ul class="nav-tabs nav">
                                      
                                      <?php echo $this->subMenuOption('competitions/current', 'Current Draws', 'active'); ?>
                                      <?php echo $this->subMenuOption('competitions/previous', 'Previous Draws', 'active'); ?>
                                      <?php echo $this->subMenuOption('competitions/ko', 'KO Info &amp; Sign-up', 'active'); ?>


                                       </ul>
                                </div>
                                