<div class="filters">
                                       <ul class="nav-tabs nav">
                                      
                                      
                                     <li  class="active"  ><a href="<?php echo $this->url('competitions/current'); ?>">Current Draws</a></li>
                                      <li ><a href="<?php echo $this->url('competitions/previous'); ?>">Previous Draws</a></li>
                                      <li ><a href="<?php echo $this->url('competitions/ko'); ?>">KO Info &amp; Sign-up</a></li>
                                        
                                       

                                       </ul>
                                </div>
                                