<div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>DIRECTORIES</h1>
                      </div>
                      
                      
                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                                <div class="filters">
                                      <ul class="nav-tabs nav">
                                      <li class="active" ><a href="<?php echo $this->url('directories', ['id' => 1]); ?>">Coaches</a></li>
                                      <li   ><a href="<?php echo $this->url('directories', ['id' => 2]); ?>">Stringers</a></li>
                                      <li ><a href="<?php echo $this->url('directories', ['id' => 3]); ?>">Holiday Camps</a></li>
                                      <li ><a href="<?php echo $this->url('directories', ['id' => 4]); ?>">Physios</a></li>
                                      <li  ><a href="<?php echo $this->url('directories', ['id' => 5]); ?>">Equipment</a></li>
                                     
                                       </ul>
                                </div>
                                
                                <hr>
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-lg-10 col-lg-offset-1">
                               
                      To begin your search for coaches in your area, please enter the first part of the postcode below and click the search button.

                          <br><br>
                          Please contact <a href="mailto:directory@londontennis.co.uk">directory@londontennis.co.uk</a> for details on how to get your business listed in this directory.
                           
                           <hr>
                            </div>
                            
                            <div class="col-lg-10 col-lg-offset-1">
                                <div class="table-responsive">
                                <table class="table table-striped table-directories">
                                    <thead>
                                      
                                        <tr>
                                            
                                        <th>Name</th>
                                        <th>Venue</th>
                                        <th>Contact</th>
                                        <th>Description</th>
                                        </tr>
                                        
                                    </thead>
                                    
                                    <tbody>
                                       
                                     <!-- single Direcotry   -->
                                        <tr >
                                             <td class="directory-img" >
                                              <span class="img-thumb center-block"><img src="img/profile.jpg" alt=""></span>
                                             <p>Paul Barton</p>
                                             </td>
                                             
                                             <td>
                                                 <a href="#court-page">Wimbledon Park</a>
                                                 <p>Home Park <br> Rd Wimbledon <br>
SW19 7HX</p>
                                                 
                                             </td>
                                             
                                             <td class="contact-directory">
                                                
                                                 <a href="#webpage">Website</a>
                                                 <a href="#sendmessage">Send a message</a>
                                                  <p>07961 170675</p>
                                                  
                                             </td>
                                             
                                             <td  class="description" >
                                             <div class="description-body short">
                                                     Paul has 20 years international coaching experience and has worked with players of all levels during this time. Paul holds LTA level 1 and 2 qualifications and is a member of the British Tennis Coaches association. 

Paul runs lessons for juniors and adults and offers group and private sessions to players of all levels. 

Junior lessons run term time and in the holidays and are for children of 4 years and over. 

Adult group and individual lessons run both in the evenings and at the weekends. 

To receive updates from Paul about lessons in Wimbledon park, send an email to paul@londontennis.co.uk requesting to be added to his email list.
                                                 
                                                
                                                 
                                                 
                                                 
                                             </div>
                                        <a href="#readmore">Read More...</a>
                                             </td>
                                        </tr>
                          <!-- End of single Direcotry   -->
                                        
                                         <!-- single Direcotry   -->
                                        <tr >
                                             <td class="directory-img" >
                                              <span class="img-thumb center-block"><img src="img/players/128.jpg" alt=""></span>
                                             <p>Mark Will</p>
                                             </td>
                                             
                                             <td>
                                                 <a href="#court-page">Wimbledon Park</a>
                                                 <p>Home Park <br> Rd Wimbledon <br>
SW19 7HX</p>
                                                 
                                             </td>
                                             
                                             <td class="contact-directory">
                                                
                                                 <a href="#webpage">Website</a>
                                                 <a href="#sendmessage">Send a message</a>
                                                  <p>07961 170675</p>
                                                  
                                             </td>
                                             
                                             <td  class="description" >
                                             <div class="description-body short">
       Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis beatae, consectetur sed suscipit eligendi unde quaerat aut rerum quia! Vel nostrum eaque, cum sint. Quos, magnam ullam dolor aspernatur 
                                                 
                                                
                                                 
                                                 
                                                 
                                             </div>
                                        <a href="#readmore">Read More...</a>
                                             </td>
                                        </tr>
                          <!-- End of single Direcotry   -->
                                       
                                        <!-- single Direcotry   -->
                                        <tr >
                                             <td class="directory-img" >
                                              <span class="img-thumb center-block"><img src="img/players/130.jpg" alt=""></span>
                                             <p>Mark Will</p>
                                             </td>
                                             
                                             <td>
                                                 <a href="#court-page">Wimbledon Park</a>
                                                 <p>Home Park <br> Rd Wimbledon <br>
SW19 7HX</p>
                                                 
                                             </td>
                                             
                                             <td class="contact-directory">
                                                
                                                 <a href="#webpage">Website</a>
                                                 <a href="#sendmessage">Send a message</a>
                                                  <p>07961 170675</p>
                                                  
                                             </td>
                                             
                                             <td  class="description" >
                                             <div class="description-body short">
Sartorial taxidermy deep v, whatever Etsy Echo Park shabby chic butcher Tumblr beard banjo fap Banksy. Meh actually pug fashion axe, chillwave pickled migas vegan food truck yr squid tilde Pinterest. XOXO paleo sartorial freegan actually wayfarers. Blue Bottle chillwave kogi, cred typewriter small batch forage cornhole post-ironic gluten-free PBR YOLO. Quinoa polaroid b
                                                 
                                                
                                                 
                                                 
                                                 
                                             </div>
                                        <a href="#readmore">Read More...</a>
                                             </td>
                                        </tr>
                          <!-- End of single Direcotry   -->
                                       
                                       
                                        <!-- single Direcotry   -->
                                        <tr >
                                             <td class="directory-img" >
                                              <span class="img-thumb center-block"><img src="img/players/132.jpg" alt=""></span>
                                             <p>Casper Bawol</p>
                                             </td>
                                             
                                             <td>
                                                 <a href="#court-page">Wimbledon Park</a>
                                                 <p>Home Park <br> Rd Wimbledon <br>
SW19 7HX</p>
                                                 
                                             </td>
                                             
                                             <td class="contact-directory">
                                                
                                                 <a href="#webpage">Website</a>
                                                 <a href="#sendmessage">Send a message</a>
                                                  <p>07961 170675</p>
                                                  
                                             </td>
                                             
                                             <td  class="description" >
                                             <div class="description-body short">
Food truck crucifix roof party shabby chic Godard selfies, cornhole actually Carles Odd Future biodiesel put a bird on it. Readymade bespoke mumblecore, post-ironic fap fixie Schlitz bicycle rights Banksy. Flexitarian 90's biodiesel lomo. Actually tofu tilde Pinterest VHS, next level sartorial meh Williamsburg scenester keffiyeh Banksy forage letterpress mumblecore. Hoodie organic YOLO, Pitchfork stumptown distillery chillwave Vice lumbersexual church-key Marfa meh. Readymade Wes Anderson American Apparel, cold-pressed irony semiotics shabby chic PBR. Food truck occupy Odd Future flannel selfies, Carles Bushwick chillwave kale chips.
                                                 
                                                
                                                 
                                                 
                                                 
                                             </div>
                                        <a href="#readmore">Read More...</a>
                                             </td>
                                        </tr>
                          <!-- End of single Direcotry   -->
                                       
                                       
                                        <!-- single Direcotry   -->
                                        <tr >
                                             <td class="directory-img" >
                                              <span class="img-thumb center-block"><img src="img/players/133.jpg" alt=""></span>
                                             <p>Robert Savoy</p>
                                             </td>
                                             
                                             <td>
                                                 <a href="#court-page">Wimbledon Park</a>
                                                 <p>Home Park <br> Rd Wimbledon <br>
SW19 7HX</p>
                                                 
                                             </td>
                                             
                                             <td class="contact-directory">
                                                
                                                 <a href="#webpage">Website</a>
                                                 <a href="#sendmessage">Send a message</a>
                                                  <p>07961 170675</p>
                                                  
                                             </td>
                                             
                                             <td  class="description" >
                                             <div class="description-body short">
Cred tattooed trust fund farm-to-table. Tousled viral drinking vinegar, locavore pour-over forage semiotics cold-pressed fixie Marfa Blue Bottle kale chips blog. Next level quinoa raw denim, cray fixie Schlitz before they sold out Thundercats banh mi 3 wolf moon umami freegan pork belly small batch. Echo Park put a bird on it 90's Williamsburg church-key, authentic wayfarers gentrify photo booth 
                                                 
                                                
                                                 
                                                 
                                                 
                                             </div>
                                        <a href="#readmore">Read More...</a>
                                             </td>
                                        </tr>
                          <!-- End of single Direcotry   -->
                                        
                                        
                                        
                                        
                                        
                                    </tbody>
                               
                                 
                                 
                                 
                                </table>
                            </div>
                                
                                
                            </div>
                            
                            
  
                        </div>
                        
                        
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>