<div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>ACCOUNT</h1>
                      </div>
                      
                      
                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                                <?php  echo $this->partial('application/auth/partials/subnav.phtml'); ?>
                                
                                <p class="description">A star (*) next to a field name donates that it is a required field.
<br><br>
You must be over 18 to join London Tennis.
</p>
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-lg-10 col-lg-offset-1 col-sm-10 col-sm-offset-1 ">
                                <form class="form-horizontal" role="form" name="registerform" method="post">
  <div class="form-group">
   <span  class="help-block ">Please enter your name.</span>
    <label for="player-name" class="col-sm-2 control-label">Forenames *</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="player-name" name="firstname" >
    </div>
  </div>
  <div class="form-group">
   
    <label for="player-name" class="col-sm-2 control-label">Surname *</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="player-name" name="surname" >
    </div>
  </div>
  
  <div class="form-group">
   <span  class="help-block ">If you heard about London Tennis through a coach or other business, please type their name below.</span>
    <label for="player-name" class="col-sm-2 control-label">Referrer</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="player-name" name="coach" >
    </div>
  </div>
  
  <div class="form-group">
   <span  class="help-block ">Your email address will not be given away to another company.</span>
    <label for="player-name" class="col-sm-2 control-label">Email *</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="player-name"  name="emailaddresse">
    </div>
  </div>
  
    
       <div class="form-group">
   <span  class="help-block ">Please select a username and password with which you will be able log in to the site.</span>
    <label for="player-name" class="col-sm-2 control-label">Username *</label>
  
    <div class="col-sm-4">
      <input type="text" class="form-control" id="player-name"  name="name">

    </div>
  </div>  
  
   <div class="form-group">
  
    <label for="player-name" class="col-sm-2 control-label">Password *</label>

    <div class="col-sm-4">

      <input type="password" class="form-control" id="player-name"  name="password1">
 
    </div>
  </div>  
  
   <div class="form-group">
   
    <label for="player-name" class="col-sm-2 control-label">Repeat Password *</label>
    <div class="col-sm-4">

      <input type="password" class="form-control" id="player-name"  name="password2">
    </div>
  </div>  
  
  
    <div class="form-group">
   <span  class="help-block ">Please enter some details about yourself, your location, playing preferences, etc... that you would like other members of London Tennis to view. This information can be changed at any time after registration.
<br><br>
You may leave this blank initially if you wish but you will need to complete it in order for your profile to appear on searches.</span>
    <label for="player-name" class="col-sm-2 control-label">Profile</label>
  
    <div class="col-sm-4">
      <textarea class="form-control"  name="profiletext" rows="3"></textarea>

    </div>
  </div>  
  
  
    <div class="form-group">
   <span  class="help-block ">Please enter the first part of your post code.</span>
    <label for="player-name" class="col-sm-2 control-label">Postcode *</label>
  
    <div class="col-sm-2">
      <input type="text" class="form-control" id="player-name"  name="zipcode" placeholder="eg. SW6">

    </div>
  </div>  
  
  
  
     <div class="form-group">
    <label  class="col-sm-2 control-label">Gender *</label>
    <div class="col-sm-10">
     
<select name="sex" class="form-control gender">
     <option value="0">Please Select..</option>
     <option value="1">Male</option>
     <option value="2">Female</option>
   </select>
     
      
    </div>
  </div>
  
  
  
   <div class="form-group">
   <span class="help-block ">	Please select a standard that best describes your ability. Your rating can be changed after registration.<br>
   <a href="#help">Click here to read more details about these ratings in a new window</a>
 	</span>
    <label  class="col-sm-2 control-label">Your Standard *</label>
    <div class="col-sm-10">
     
<select name="parkrating" class="form-control park-rating">
     <option value="0">-</option>
     <option value="1">ITN 1 - World Standard</option>
     <option value="2">ITN 2 - National Standard</option>
     <option value="3">ITN 3 - County Standard</option>
     <option value="4">ITN 4 - Top Club Level</option>
     <option value="5">ITN 5 - High Intermediate</option>
     <option value="6">ITN 6 - Middle Intermediate</option>
     <option value="7">ITN 7 - Low Intermediate</option>
     <option value="8">ITN 8 - Good Recreational</option>
     <option value="9">ITN 9 - Recreational</option>
      <option value="10">ITN 10 - Starter</option>
      </select>
     
      
    </div>
  </div>
  
  
  
  <ul class="terms col-lg-10 col-lg-offset-2">
      <li>By clicking the register button you are agreeing to London <a href="#terms">Tennis Terms of Service.</a></li>
      <li>Please read our  <a href="#terms">privacy statement.</a></li>
  </ul>
  

  
<div class="submit col-lg-10 ">
   <button type="submit" name="findplayerbutton" class="btn btn-green">Register</button>  
    
</div>



</form>
                               
                                
                            </div>
                            
                            
                        </div>
                        
                        
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>