<div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>ACCOUNT</h1>
                      </div>
                      
                      
                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">

                                <?php  echo $this->partial('application/auth/partials/subnav.phtml'); ?>
                                
                                <p class="description">	Please <a href="#remind">click here</a> to receive a password reminder if you are having problems to login.

</p>
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-lg-10 col-lg-offset-1 col-sm-10 col-sm-offset-1 ">
                                <form class="form-horizontal" role="form" name="login" method="post">
  <div class="form-group">
 
    <label for="player-name" class="col-sm-2 control-label">Email or Username</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="player-name" name="loginemail" >
    </div>
  </div>
  <div class="form-group">
   
    <label for="player-name" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="player-name" name="loginpassword" >
    </div>
  </div>

  

  
<div class="submit col-lg-10 ">
   <button type="submit"  class="btn btn-green">Login</button>  
    
</div>



</form>
                               
                                
                            </div>
                            
                            
                        </div>
                        
                        
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>