<div class="container paper">
          <div class="shadow"></div>
           <div class="row">
               <div class="col-lg-12">
                   <div class="content">
                      <div class="title">
                          <h1>ACCOUNT</h1>
                      </div>
                      
                      
                     
                      <div class="paper-content">
                        <div class="row">
                            <div class="col-lg-10 col-sm-10 col-sm-offset-1 col-lg-offset-1">
                                <?php  echo $this->partial('application/auth/partials/subnav.phtml'); ?>
                                
                                <p class="description">	Press 'send' and we will send you an email with details on how to reset your password.
</p>
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-lg-10 col-lg-offset-1 col-sm-10 col-sm-offset-1 ">
                                <form class="form-horizontal" role="form" name="login" method="post">
  <div class="form-group">
 
    <label for="player-name" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="player-name" name="emailaddressl" >
    </div>
  </div>
  
  

  
<div class="submit col-lg-10 ">
   <button type="submit"  class="btn btn-green">SEND</button>  
    
</div>



</form>
                               
                                
                            </div>
                            
                            
                        </div>
                        
                        
                     </div>  
                    
                   </div>
                   
               </div>
               
           </div>
           
</div>