

<div class="row">

	<div class="col-lg-12 ">



		<div class="box-profile-details clearfix">
			<div class="col-lg-3 col-sm-3 ">
				<span class="img-thumb"> <img src="/img/profile.jpg" alt="">
				</span>

			</div>

			<div class="col-lg-9 profile-bubble col-sm-9  ">
				<div class="box-about-details">
					<p>I coach at Wimbledon Park. I run London Tennis and I am the
						founder of it. I have little time to play, though love a few tie
						breaks here and there, can still play to a high level when match
						tight.</p>

				</div>

				<div class="links">
					<a class="btn btn-green" href="my-account-inbox.html">Send Message</a>
					<a class="btn btn-green"
						href="<?php echo $this->view->url('players/profile', ['playerid' => $this->player['id']]) ?>">View
						Full profile</a>

				</div>
			</div>

		</div>
		<hr />
		<div class="box-player-stats clearfix">

			<div class="col-lg-6">
				<table class="table box-stats-table table-bordered">
					<thead>
						<tr>
							<td colspan="2">
								<p class="text-center">Player Profile</p>
							</td>
						</tr>

					</thead>

					<tbody>
						<tr>
							<td>Name</td>
							<td>Paul Barton</td>
						</tr>

						<tr>
							<td>Gender</td>
							<td>Male</td>
						</tr>
						<tr>
							<td>Joined</td>
							<td>29 Mar '01</td>
						</tr>
						<tr>
							<td>User Rating</td>
							<td>-</td>
						</tr>
						<tr>
							<td>LTA Number</td>
							<td>-</td>
						</tr>
						<tr>
							<td>LTa Rating</td>
							<td>-</td>
						</tr>


					</tbody>


				</table>

			</div>

			<div class="col-lg-6">
				<table class="table box-stats-table table-bordered">
					<thead>
						<tr>
							<td colspan="2">
								<p class="text-center">Tennis Preferences</p>
							</td>
						</tr>

					</thead>

					<tbody>
						<tr>
							<td>Play Radius</td>
							<td>1 miles of SW19</td>
						</tr>

						<tr>
							<td>Opponents</td>
							<td>Male</td>
						</tr>
						<tr>
							<td>Format</td>
							<td>Singles</td>
						</tr>
						<tr>
							<td>Times</td>
							<td>-</td>
						</tr>
						<tr>
							<td>Home Venue</td>
							<td>Wimbledon Park</td>
						</tr>



					</tbody>


				</table>

			</div>


		</div>


		<div class="box-player-stats clearfix">

			<div class="col-lg-6">
				<table class="table box-stats-table table-bordered">
					<thead>
						<tr>
							<td colspan="2">
								<p class="text-center">Performance</p>
							</td>
						</tr>

					</thead>

					<tbody>
						<tr>
							<td>Rank</td>
							<td>Unrated *</td>
						</tr>

						<tr>
							<td>Points</td>
							<td>Unrated</td>
						</tr>
						<tr>
							<td>Percentile</td>
							<td>Unrated</td>
						</tr>
						<tr>
							<td>W/L/D</td>
							<td>15/4/1</td>
						</tr>



					</tbody>


				</table>

			</div>

			<div class="col-lg-6">
				<table class="table box-stats-table table-bordered">
					<thead>
						<tr>
							<td colspan="2">
								<p class="text-center">Playing History</p>
							</td>
						</tr>

					</thead>

					<tbody>
						<tr>
							<td>Last Played</td>
							<td>09 Jan '14</td>
						</tr>

						<tr>
							<td>Unique Opponents</td>
							<td>9</td>
						</tr>
						<tr>
							<td>Unique Venues</td>
							<td>4</td>
						</tr>
						<tr>
							<td>Friendly Matches</td>
							<td>20</td>
						</tr>
						<tr>
							<td>League Matches</td>
							<td>2</td>
						</tr>
						<tr>
							<td>Knockout Matches</td>
							<td>1</td>
						</tr>


					</tbody>


				</table>

			</div>


		</div>

		<div class="box-profile-notes">
			<p>* A player has a rating if he or she has played at least five
				unique opponents and at least one match in the past twelve months.
				There are currently 500 ranked players. More points will be awarded
				for beating better players. Ratings are updated daily.</p>

		</div>

	</div>

</div>
